### ISSUE TITLE
KubernetesDiscoveryClient  cause OutOfMemoryError

### ISSUE THREAD

**Issue by he953481025-debug** [spring-cloud/spring-cloud-kubernetes#1019] opened 2022-05-25 01:48 UTC
1. version
 spring-cloud-kubernetes version:1.1.6.RELEASE
 kubernetes on aliyun  1.18.8-aliyun.1 
2. program arguments
 -Xms1024m -Xmx2048m -XX:MaxDirectMemorySize=32m -Xss512k -Xtune:virtualized -XX:+HeapDumpOnOutOfMemoryError
3. heapDumpAnalyse
![image](https://user-images.githubusercontent.com/67448461/170161571-cc1a6fef-a758-4071-aa5b-3182e1dd5c47.png)

**Comment by ryanjbaxter** [comment] 2022-05-25 07:53
Can you please try and reproduce this with Spring Cloud 2021.0.2?

**Comment by he953481025-debug** [comment] 2022-05-25 08:37
> 
This problem occured in our production environment.It is not allowed to switch versions at will. Figure show the spring version
![image](https://user-images.githubusercontent.com/67448461/170218997-57a77b53-bf5b-42bd-8cdb-9dfce6837093.png)

**Comment by ryanjbaxter** [comment] 2022-05-25 10:01
We no longer support Hoxton that is why I am asking to try and reproduce with a version we do support
https://spring.io/projects/spring-cloud-kubernetes#support

**Comment by spring-cloud-issues** [comment] 2022-06-01 10:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-06-08 10:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-06-08 10:05 UTC
Labels: waiting for feedback, feedback-reminder
