### ISSUE TITLE
KubernetesClientException when trying to start Spring Boot microservice on Kubernetes

### ISSUE THREAD

**Issue by angheladrianclaudiu** [spring-cloud/spring-cloud-kubernetes#216] opened 2018-07-13 09:14 UTC
I am getting this exception when trying to start a Spring Boot microservice (which is Spring Boot Zuul gateway, but I don't think it matters too much) on Kubernetes:

```
o.s.c.kubernetes.StandardPodUtils.internalGetPod(66) - Failed to get pod with name:[podname-nqm46]. You should look into this if things aren't working as you expect. Are you missing serviceaccount permissions?
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/pods/podname-nqm46. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "podname-nqm46" is forbidden: User "system:serviceaccount:default:default" cannot get pods in the namespace "default".
```

Any idea why?

**Comment by geoand** [comment] 2018-07-13 09:22
This most likely has to do with RBAC control in Kubernetes. 

It seems like you have not specified a service account for the Pod that the application is running in (and hence `default` is being used). To see how to configure a service account for a Pod check out [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/).
Furthermore the `default` service account in the namespace you are running the Pod in (which is the `default` namespace) does not have any extra Roles assigned to it (which is the default behavior).

Although you could grant the Role to the default user, the best approach would be to create ServiceAccount, use that in the Pod and grant that service  account the necessary roles.

Check out [this](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) for all the details.

**Comment by angheladrianclaudiu** [comment] 2018-07-13 11:36
Thank you. 
Working now. I made the proper configuration to my setup.

**Comment by geoand** [comment] 2018-07-13 11:41
You're welcome, go to hear it's working!

**Comment by angheladrianclaudiu** [comment] 2018-07-13 11:59
It seems I have another one that I didn't pick up from the log in the first place:

```
org.springframework.context.ApplicationContextException: Failed to start bean 'kubernetesDiscoveryLifecycle'; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [null]  failed.
```

**Comment by geoand** [comment] 2018-07-13 12:46
Can you please provide some more information about what you are doing that results in such an error?

**Comment by angheladrianclaudiu** [comment] 2018-07-13 12:50
I want to start it up. Below more info from stacktrace.

```
13-07-2018 11:57:16.317 [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext.refresh(551) - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'kubernetesDiscoveryLifecycle'; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [null]  failed.
13-07-2018 11:57:16.319 [main] INFO  o.s.c.n.zuul.ZuulFilterInitializer.contextDestroyed(77) - Stopping filter initializer
13-07-2018 11:57:16.359 [main] INFO  o.s.b.a.e.jmx.EndpointMBeanExporter.destroy(449) - Unregistering JMX-exposed beans on shutdown
13-07-2018 11:57:16.363 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter.destroy(449) - Unregistering JMX-exposed beans on shutdown
13-07-2018 11:57:16.363 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter.unregisterBeans(241) - Unregistering JMX-exposed beans
13-07-2018 11:57:16.401 [main] WARN  c.n.c.sources.URLConfigurationSource.<init>(121) - No URLs will be polled as dynamic configuration sources.
13-07-2018 11:57:16.402 [main] INFO  c.n.c.sources.URLConfigurationSource.<init>(122) - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
13-07-2018 11:57:16.486 [main] INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer.logAutoConfigurationReport(101) - 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
13-07-2018 11:57:16.498 [main] ERROR o.s.boot.SpringApplication.reportFailure(771) - Application startup failed
org.springframework.context.ApplicationContextException: Failed to start bean 'kubernetesDiscoveryLifecycle'; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [null]  failed.
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at ro.noian.pago.EdgeApplication.main(EdgeApplication.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [null]  failed.
```

**Comment by geoand** [comment] 2018-07-13 13:01
I see `Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` which makes suspicious... Are you sure that the certificates in your cluster are setup properly?

**Comment by angheladrianclaudiu** [comment] 2018-07-13 13:09
I noticed that, but I don't understand what endpoint is it trying to connect to. The cluster was spinned up with Rancher, and there is a SSL certificate setup, but I don't understand exactly what endpoint is it trying to connect to.

This also worries me: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [null]  failed.

**Comment by geoand** [comment] 2018-07-13 13:33
A call is being made the Kubernetes API. 

Have you tried deploying the application to a test cluster created for example by Minikube?

Do you have a sample project that is exhibiting  this behavior that I could  try?

**Comment by angheladrianclaudiu** [comment] 2018-07-13 13:43
It works on local Minikube, but checking the .kube/config file on Minikube and in the cluster I see that they are quite different.
Locally there is a minikube user with client-certificate and client-key. On the cluster however, there is an user with some token trying to connect.

Unfortunately I can't setup a sample project to test now. I will try to put one up shortly.

**Comment by geoand** [comment] 2018-07-13 13:46
Ok, thanks

**Comment by angheladrianclaudiu** [comment] 2018-07-13 14:43
Here you go @geoand try this one: https://github.com/angheladrianclaudiu/zuul-kubernetes

**Comment by geoand** [comment] 2018-07-13 14:44
Great, I'll take a look on Monday most likely, thanks

**Comment by geoand** [comment] 2018-07-17 12:47
@angheladrianclaudiu I tried the sample locally and it worked for me without problems.

**Comment by Salaboy** [comment] 2018-09-15 08:33
@angheladrianclaudiu @geoand I have these projects with some extra roles, role bindings and service accounts configurations to be able to interact with the Kube API from inside a pod: 
https://github.com/Salaboy/s1p_gateway/tree/master/charts/s1p-gateway/templates

Important to notice the deployment.yaml file descriptor that includes a reference to the service account. 
This is working as expected in different Kubernetes Flavours (GKE, PKS, AWS + Kops)

**Comment by Salaboy** [comment] 2018-09-15 08:34
@spencergibb I think that we can close this issue and open a documentation issue to cover this extra descriptors that are needed.

**Closed** 2018-11-26 14:35 UTC
Labels: waiting-for-triage

**Comment by nidhi5885** [comment] 2020-06-03 12:56
It is still an issue for me. Tried everything mentioned in the comments. I have created a new issue as this has been closed.
#560
