### ISSUE TITLE
Is there a way to listen for changes on the available services?

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#254] opened 2018-10-16 00:04 UTC
RIght now I have a method annotated with `@Scheduled` that ticks every 30 seconds and gets the list of all the services:

`List<String> services = discoveryClient.getServices();`

While the method works, and I get a list of all the current services, for some reason doing this triggers a NullPointerException in KubernetesCatalogWatch.java:65: Error watching Kubernetes Services

> java.lang.NullPointerException: null at org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatch.lambda$catalogServicesWatch$2(KubernetesCatalogWatch.java:65) ~[spring-cloud-kubernetes-discovery-0.3.0.RELEASE.jar!/:0.3.0.RELEASE] at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181] at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_181] at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_181] at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[na:1.8.0_181] at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_181] at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_181] at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[na:1.8.0_181] at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_181] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181] at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_181] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181] at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_181] at org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatch.catalogServicesWatch(KubernetesCatalogWatch.java:66) ~[spring-cloud-kubernetes-discovery-0.3.0.RELEASE.jar!/:0.3.0.RELEASE] at org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatch$$FastClassBySpringCGLIB$$b5625982.invoke(<generated>) [spring-cloud-kubernetes-discovery-0.3.0.RELEASE.jar!/:0.3.0.RELEASE] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) [spring-aop-5.0.9.RELEASE.jar!/:5.0.9.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.9.RELEASE.jar!/:5.0.9.RELEASE] at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) [spring-aop-5.0.9.RELEASE.jar!/:5.0.9.RELEASE] at org.springframework.cloud.sleuth.instrument.scheduling.TraceSchedulingAspect.traceBackgroundThread(TraceSchedulingAspect.java:68) [spring-cloud-sleuth-core-2.0.1.RELEASE.jar!/:2.0.1.RELEASE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181] at

**Comment by Alos** [comment] 2018-10-16 00:48
I removed the `@EnableScheduling` in my application and the error went away. It looks like if there is a another `@Scheduled` method in the app `KubernetesCatalogWatch ` stops updating too.  Is there any other way to listen for these kinds of events?

**Comment by Alos** [comment] 2018-10-16 17:40
I've styled the logs better. You can basically reproduce this by creating a Spring Boot app with Spring Cloud Kubernetes and adding a `@Scheduled` annotation to any method and the `@EnableScheduling` to the main application class. Let me know if you are unable to replicate it!

**Comment by geoand** [comment] 2018-10-16 17:48
Thanks, 

I will create a dummy app and check this out soon hopefully

**Comment by Alos** [comment] 2018-10-16 18:04
I've done a little more testing and it looks like service discovery is not broken by this. The NPE keeps happening but nothing appears to be affected.

**Comment by geoand** [comment] 2018-10-17 06:06
After performing some debugging, I am pretty sure that this is a duplicate of #238 which has been fixed in `master`. 

@Alos Would you be willing to test your application against `master` so we have verify?

Thanks

**Comment by salaboy** [comment] 2018-10-31 11:05
@geoand @spencergibb tested in master and this is fixed. So we should close this issue.

**Closed** 2018-10-31 12:19 UTC
Labels: waiting-for-triage
