### ISSUE TITLE
ConfigMapPropertySource getData returns an empty hashMap

### ISSUE THREAD

**Issue by scizeron** [spring-cloud/spring-cloud-kubernetes#474] opened 2019-10-14 14:21 UTC
Hi,
In my context, I have a spring-boot app using a service account with a specific role (GET my config-map). 
Now I have updated my app with spring-cloud-kubernetes from 1.0.1 to 1.0.2 and it fails.
In 1.0.1, the getData method was very straightforward as you can see below :
ConfigMap map = StringUtils.isEmpty(namespace)
					? client.configMaps().withName(name).get()
					: client.configMaps().inNamespace(namespace).withName(name).get();

Now, when this first config map is loaded, it tries to load a config map with the '-kubernetes' suffix.
When the last one fails (for security reason 403 in my case), it returns a empty hashMap whereas the main config map has been successfully loaded.
Why not returning the main config map instead of forcing people to add a new resource name with a "-kubernetes" suffix in the role definition ?

**Comment by ryanjbaxter** [comment] 2020-03-04 22:05
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2020-03-11 22:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-03-18 22:09
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-03-18 22:09 UTC
Labels: feedback-reminder, waiting for feedback
