### ISSUE TITLE
can not start up application, io.kubernetes.client.openapi.ApiException:

### ISSUE THREAD

**Issue by dragontree101** [spring-cloud/spring-cloud-kubernetes#1018] opened 2022-05-24 02:49 UTC
start up springboot application,  have some exception

version is

springboot 2.6.7
spring-cloud-kubernetes 2.1.2

```
2022-05-24 10:48:26.993] [informer-controller-V1Endpoints] [hn-framework-sample-web] [] [] INFO  io.kubernetes.client.informer.cache.Controller - informer#Controller: ready to run resync & reflector runnable
[2022-05-24 10:48:26.992] [informer-controller-V1Service] [hn-framework-sample-web] [] [] INFO  io.kubernetes.client.informer.cache.Controller - informer#Controller: ready to run resync & reflector runnable
[2022-05-24 10:48:26.995] [informer-controller-V1Service] [hn-framework-sample-web] [] [] INFO  io.kubernetes.client.informer.cache.Controller - informer#Controller: resync skipped due to 0 full resync period
[2022-05-24 10:48:26.996] [informer-controller-V1Endpoints] [hn-framework-sample-web] [] [] INFO  io.kubernetes.client.informer.cache.Controller - informer#Controller: resync skipped due to 0 full resync period
[2022-05-24 10:48:27.005] [controller-reflector-io.kubernetes.client.openapi.models.V1Endpoints-1] [hn-framework-sample-web] [] [] INFO  i.k.client.informer.cache.ReflectorRunnable - class io.kubernetes.client.openapi.models.V1Endpoints#Start listing and watching...
[2022-05-24 10:48:27.005] [controller-reflector-io.kubernetes.client.openapi.models.V1Service-1] [hn-framework-sample-web] [] [] INFO  i.k.client.informer.cache.ReflectorRunnable - class io.kubernetes.client.openapi.models.V1Service#Start listing and watching...
[2022-05-24 10:48:27.989] [pool-15-thread-1] [hn-framework-sample-web] [] [] INFO  o.s.c.k.c.d.KubernetesInformerDiscoveryClient - Waiting for the cache of informers to be fully loaded..
[2022-05-24 10:48:28.112] [controller-reflector-io.kubernetes.client.openapi.models.V1Endpoints-1] [hn-framework-sample-web] [] [] ERROR i.k.client.informer.cache.ReflectorRunnable - class io.kubernetes.client.openapi.models.V1Endpoints#Reflector loop failed unexpectedly
io.kubernetes.client.openapi.ApiException:
at io.kubernetes.client.util.Watch.createWatch(Watch.java:105)
at io.kubernetes.client.util.generic.GenericKubernetesApi.watch(GenericKubernetesApi.java:761)
at io.kubernetes.client.informer.SharedInformerFactory$2.watch(SharedInformerFactory.java:269)
at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:121)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:831)
[2022-05-24 10:48:28.141] [controller-reflector-io.kubernetes.client.openapi.models.V1Service-1] [hn-framework-sample-web] [] [] ERROR i.k.client.informer.cache.ReflectorRunnable - class io.kubernetes.client.openapi.models.V1Service#Reflector loop failed unexpectedly
io.kubernetes.client.openapi.ApiException:
at io.kubernetes.client.util.Watch.createWatch(Watch.java:105)
at io.kubernetes.client.util.generic.GenericKubernetesApi.watch(GenericKubernetesApi.java:761)
at io.kubernetes.client.informer.SharedInformerFactory$2.watch(SharedInformerFactory.java:269)
at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:121)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:831)
[2022-05-24 10:48:28.988] [pool-15-thread-1] [hn-framework-sample-web] [] [] INFO  o.s.c.k.c.d.KubernetesInformerDiscoveryClient - Waiting for the cache of informers to be fully loaded..
[2022-05-24 10:48:28.990] [main] [hn-framework-sample-web] [] [] INFO  o.s.c.k.c.d.KubernetesInformerDiscoveryClient - Cache fully loaded (total 3 services) , discovery client is now available
[2022-05-24 10:48:29.113] [controller-reflector-io.kubernetes.client.openapi.models.V1Endpoints-1] [hn-framework-sample-web] [] [] INFO  i.k.client.informer.cache.ReflectorRunnable - class io.kubernetes.client.openapi.models.V1Endpoints#Start listing and watching...
[2022-05-24 10:48:29.135] [controller-reflector-io.kubernetes.client.openapi.models.V1Endpoints-1] [hn-framework-sample-web] [] [] ERROR i.k.client.informer.cache.ReflectorRunnable - class io.kubernetes.client.openapi.models.V1Endpoints#Reflector loop failed unexpectedly
io.kubernetes.client.openapi.ApiException:
at io.kubernetes.client.util.Watch.createWatch(Watch.java:105)
at io.kubernetes.client.util.generic.GenericKubernetesApi.watch(GenericKubernetesApi.java:761)
at io.kubernetes.client.informer.SharedInformerFactory$2.watch(SharedInformerFactory.java:269)
at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:121)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:831)
[2022-05-24 10:48:29.143] [controller-reflector-io.kubernetes.client.openapi.models.V1Service-1] [hn-framework-sample-web] [] [] INFO  i.k.client.informer.cache.ReflectorRunnable - class io.kubernetes.client.openapi.models.V1Service#Start listing and watching...
```
how can i slove this problem？ thx

**Comment by ryanjbaxter** [comment] 2022-08-18 00:05
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2022-08-25 00:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-09-01 00:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-09-01 00:07 UTC
Labels: waiting for feedback, feedback-reminder
