### ISSUE TITLE
ServiceInstance not injectable after upgrade to 2021.0.0 (K8S Client 2.1.0)

### ISSUE THREAD

**Issue by JWThewes** [spring-cloud/spring-cloud-kubernetes#930] opened 2021-12-06 08:20 UTC
I upgraded our project to Spring Boot 2.6.1 and Spring Cloud 2021.0.0 and now I can't inject an instance of ServiceInstance anymore.
I would have expected to get the ServiceInstance instance of the current running application. That was the case in the previous release.

**Comment by wind57** [comment] 2021-12-06 13:34
can you expand on this issue a bit? As it is right now, I don't think it is possible to triage it.

**Comment by JWThewes** [comment] 2022-02-10 10:33
Well before 2021.0.0 I was able to simply inject an instance of ServiceInstance. This happened to be the information of the actual instance (pod). For example I was able to inject ServiceInstance and call getInstanceId(). This has given me the pod id.
No I get a NoBeanDefinitionFoundException.
Currently my workaround is to use the Fabric8PodUtils and invoke currentPod().get().getMetadata().getUid()

Would be great to be able to inject the "self"ServiceInstance to have the Spring Cloud abstraction over here too.

**Comment by wind57** [comment] 2022-02-11 12:50
can you provide a simple, reproducible example, should be available on github. This way we can look into the issue and understand how to re-produce it.

**Comment by rnsd** [comment] 2022-05-18 08:24
It seems like the axon-cloud-extension (https://github.com/AxonFramework/extension-springcloud) runs into a problem related to the issue reported here. I do not have a simple reproducible github exampe, but it is thoroughly described at : https://discuss.axoniq.io/t/compatibilty-axon-springcloud-extension-with-org-springframework-cloud/3856

**Comment by ryanjbaxter** [comment] 2022-08-18 00:30
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2022-08-25 00:32
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-09-01 00:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-09-01 00:32 UTC
Labels: waiting for feedback, feedback-reminder
