### ISSUE TITLE
How to disable this for tests

### ISSUE THREAD

**Issue by sta-szek** [spring-cloud/spring-cloud-kubernetes#196] opened 2018-06-28 08:43 UTC
I want to disable it in tests because it fails in different places for different reasons:
* missing kubeconfig which cannot be provided to build enb
* not valid certificate for kube client
* requirement for connection between k8s and build env

I tried to disable it during test phase but without luck:
```
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: false
      enabled: false
```

the `discovery.enabled: false` has no effect at all -- Config is still being created and throws exception.
When I added `kubernetes.enabled: false` then I have exception:

```
Parameter 0 of method discoveryClient in org.springframework.cloud.kubernetes.discovery.KubernetesDiscoveryClientAutoConfiguration required a bean of type 'io.fabric8.kubernetes.client.KubernetesClient' that could not be found.
	- Bean method 'kubernetesClient' not loaded because @ConditionalOnProperty (spring.cloud.kubernetes.enabled) found different value in property 'spring.cloud.kubernetes.enabled'
```

Probably you are missing 
```
@ConditionalOnProperty(value = "spring.cloud.kubernetes.enabled", matchIfMissing = true)
@ConditionalOnBean(KubernetesClient.class)
``` 
on whole `KubernetesDiscoveryClientAutoConfiguration.class`

and `@ConditionalOnMissingBean(DiscoveryClient.class)` on method `discoveryClient`

**Comment by Salaboy** [comment] 2018-09-15 08:30
@sta-szek you are totally right.. I will work to fix this one

**Comment by geoand** [comment] 2018-09-25 12:31
@salaboy Have you started work on this? If not, I can pick up the issue

**Comment by geoand** [comment] 2018-09-25 12:36
This does indeed seem like a duplicate of #183

**Comment by piotr-napadlek** [comment] 2018-10-01 08:39
Any progress with this one? Seems to be nice and easy fix but makes it impossible to disable kubernetes discovery client for tests in a clean way - we need to mock kubernetesClient bean.

**Comment by salaboy** [comment] 2018-10-01 08:44
@geoand @piotr-napadlek I haven't started on this one yet. I am just catching up with stuff after @s1p
@piotr-napadlek you are right.. it will complicate the testing. but I think that we need to change the tests as well. I am not happy with the way that we are testing stuff.

**Comment by geoand** [comment] 2018-10-01 08:46
@salaboy We can talk about this as well I guess when you are done catching up after s1p and you have some time to talk :)

**Comment by spencergibb** [comment] 2018-10-30 16:52
Closing duplicates #183

**Closed by spencergibb** 2018-10-30 16:52 UTC
Labels: waiting-for-triage
