### ISSUE TITLE
Cluster-wide configuration reload capability

### ISSUE THREAD

**Issue by cz4rny** [spring-cloud/spring-cloud-kubernetes#1027] opened 2022-06-06 16:50 UTC
**Is your feature request related to a problem? Please describe.**
When following good k8s practices people deploy each application in their own namespace. As I understand the [spring-cloud-kubernetes-configuration-watcher](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#spring-cloud-kubernetes-configuration-watcher) is looking for `ConfiMap`s and `Secret`s in the `Namespace` it is deployed to.

This means, that one would need to add a new instance of the spring-cloud-kubernetes-configuration-watcher per each of theri namespace for each of their apps.

**Describe the solution you'd like**
A way better solution would upgrade that controller to see cluster-wide namespaces and ping SB apps to `/refresh` in any of the `Namespace`s. Essentially one master controller for Spring Boot dynamic config reload per cluster.

An obvious benefit is, that this service would be mostly provided by platform admins. So one less thing business-app devs don't need to worry about.

**Describe alternatives you've considered**
I've tried to be cheeky and upgrade the `Role` and `RoleBinding` to `ClusterRole` and `ClusterRoleBinding` hoping, that the microservice would start scanning all namespaces on the cluster. That isn't the case.

I know of the [PropertySource Reload](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#propertysource-reload), however, it seems to be deprecated and also limited to the same `Namespace` scoping.

**Comment by ryanjbaxter** [comment] 2022-06-06 23:39
Duplicate of #814

**Closed by ryanjbaxter** 2022-06-06 23:39 UTC
Labels: waiting-for-triage

**Comment by wind57** [comment] 2022-07-15 03:49
> I know of the [PropertySource Reload](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#propertysource-reload), however, it seems to be deprecated

It is deprecated indeed, but it has just seen some refreshes and improvements (fabric8 one). So for example, release `3.0.x` of spring-cloud-kubernetes still has this capability and it has been improved even.

> and also limited to the same Namespace scoping.

Not anymore. The documentation for the `3.0.x` will provide additional details on how you can specify the namespace and even narrow to specific configmaps/secrets.

**Comment by cz4rny** [comment] 2022-09-05 13:37
@wind57 Thanks for that tip. So the capability is there in the spring boot kubernetes ecosystem. However, the PropertySource still is being deprecated and the documentation points towards the kubernetes configuration watcher. Ergo, if this isn't implemented here, we'll loose this capability.
