### ISSUE TITLE
KubernetesServerList is not able to fetch endpoints for all namespaces

### ISSUE THREAD

**Issue by doernbrackandre** [spring-cloud/spring-cloud-kubernetes#163] opened 2018-03-12 09:41 UTC
Hi,

during our investigations how to handle services deployed in several projects within openshift using Zuul as api gateway we ran into a major problem when trying to fetch pods/endpoints

Scenario:
- a Zuul as api gateway using spring-cloud-starter-kubernetes-netflix running a dedicated project inside openshift
- at least one downstream service which is deployed in an other project

When sticking to the fabric8's DefaultKubernetesClient implementation there are two steps needed in order to perform service discovery:

**1) Perform service discovery based on kubernetes services by invoking client.services()**
In our scenario we want to tweak this a little to discover kubernetes services with a certain label within all namespaces. For example 'example.com/stage: testing'

This step works fine by extending the DefaultKubernetesClient:

````
    @Bean
    public KubernetesClient kubernetesClient() {
        DefaultKubernetesClient client = new DefaultKubernetesClient() {
            @Override
            public MixedOperation<Service, ServiceList, DoneableService, Resource<Service, DoneableService>> services() {
                ServiceOperationsImpl serviceOperations = new ServiceOperationsImpl(httpClient, getConfiguration(), null);
                serviceOperations.withLabels(labels);

                return serviceOperations;
            }

        };

        return client;
    }
````

**2) Fetching endpoints for all discovered kubernetes services**
Here we're facing the problem: The KubernetesServerList reads the configured namespace from the configuration file/environment (for 'any namespace' this property should be null). However, as you can see in the initWithNiwsConfig() method this property is treaded as a string:

````
this.namespace = clientConfig.getPropertyAsString(KubernetesConfigKey.Namespace, client.getNamespace());
```` 

Now, in the getUpdatedListOfServers() method which is invoked to return the list of available instances, a NULL is expected in case you want to fetch all namespaces:

````
        Endpoints endpoints = namespace != null
                ? client.endpoints().inNamespace(namespace).withName(serviceId).get()
                : client.endpoints().withName(serviceId).get();
````

Now, of course, an empty string is not null so the client tries to discover endpoints for namespace: "" and it fails.

Unfortunately, even if you try to execute ````client.endpoints().withName(serviceId).get()```` it returns NULL because the kubernetes API returns 404. Maybe the API has changed?

So maybe this call should be change to something like
````
client.endpoints().inAnyNamespace().withLabel("name", serviceId).list()
````
NOTE: .withLabel("name", ServiceId) is not the correct equivalent to .withName(serviceId)
In our case we can use a alternative filter here so it's not a problem for us. But I can see that a generic solution should be implemented here.

**Comment by doernbrackandre** [comment] 2018-04-03 07:29
Hi, @spencergibb

we had planned to upstream our changes to fix the issues we've faced here. I've seen that you started  to rework this project. Are you interested in our changes? Does it make sense to PR those?

Our work includes:
* implementing the metadata in the KubernetesDiscoveryClient
* fixing the issues with client.endpoints()
* rework of the namespace logic in order to gain better control over the namespace configuration

**Comment by spencergibb** [comment] 2018-04-03 17:11
PRs welcome @doernbrackandre!

**Comment by doernbrackandre** [comment] 2018-04-04 07:33
@spencergibb What are your thoughts about the test done with Spock? Are you planning to replace them? If so, I can try to replace the tests I will break with my changes...

**Comment by Salaboy** [comment] 2018-09-15 08:28
@doernbrackandre I am also interested in this.. I see more and more people using namespaces as applications isolation boundaries. I see a lot of problems with that approach moving forward, so we might need to have some conversations about that particular topic. 

Regarding tests, I've created this issue: https://github.com/spring-cloud/spring-cloud-kubernetes/issues/236 with the intention of trying to improve how we are testing these modules. What do you have in mind for that? Maybe we can collaborate on such task.

**Comment by Salaboy** [comment] 2018-09-15 09:42
@doernbrackandre @spencergibb  the more I think about this, the more I think that we open the door for multiple other problems if we do get stuff from multiple namespaces at the same time. Namespaces in kubernetes might end up having different security policies and by design namespaces mean isolation, so things running in a namespace should be contained. If they need to interact with other services running in different namespaces they can user their public entry points. I am for sure, still thinking about this, so don't take this as an answer more just thinking out loud.

**Comment by doernbrackandre** [comment] 2018-09-17 07:36
Hi @Salaboy,
the idea is to expose routes over an API gateway based on metadata provided by the downstream service instead of using openshift's routes directly. 
Currently, you have to use a global project or you have to provide a API  gateway in every project inside openshift in order to discover services, which is not ideal from our perspective.

**Comment by Salaboy** [comment] 2018-09-17 07:51
@doernbrackandre yeah.. I would say that it is far from ideal.. but those is Openshift's specifics, based on their conventions and custom resources such as Project and Routes. The problem that I see is that if you use Discovery client to check services from multiple namespaces you will bypassing that design approach in Openshift and more in general it feels right to keep things limited to a k8s namespace from a design point of view.

**Comment by doernbrackandre** [comment] 2018-09-17 07:59
@Salaboy yes, the service account needs "cluster reader" privileges.

It would be nice to have at least the option to configure this behavior. Then, you can decide to use it or not.

**Comment by Salaboy** [comment] 2018-09-17 08:30
@doernbrackandre 👍 , that is one of the main reasons why I created this one: https://github.com/spring-cloud/spring-cloud-kubernetes/issues/233 which can be extended to be Kubernetes/Infrastructure awareness. Because for your use case is good to just have read only, but I can definitely see people trying to add business logic into how and when namespaces should be created. I haven't seen in Spring Cloud that abstraction.. but I will do some research on that side.

**Comment by doernbrackandre** [comment] 2018-09-17 09:04
@Salaboy This is not necessarily something related to spring cloud. You can keep this logic of the namespaces inside the KubernetesClient

**Comment by Salaboy** [comment] 2018-09-17 09:44
@doernbrackandre I thought that the KubernetesClient  (fabric8) already support that. Or you mean the Kubernetes Discovery Client?

**Comment by doernbrackandre** [comment] 2018-09-17 11:15
@Salaboy yes, the fabric8 client. The client should support this, but unfortunately there is a bug (see my first post)

**Comment by Salaboy** [comment] 2018-09-17 14:07
@doernbrackandre :+1 let's try to get that one fixed and try to understand their release cycle.

**Comment by doernbrackandre** [comment] 2018-09-18 07:35
@Salaboy good morning!

We've fixed this by overriding the DefaultKubernetesClient's endpoints() method:
````
    @Override
    public MixedOperation<Endpoints, EndpointsList, DoneableEndpoints, Resource<Endpoints, DoneableEndpoints>> endpoints() {
        if (StringUtils.isEmpty(getNamespace())) {
            EndpointsOperationsImpl endpointsOperations = new EndpointsOperationsImpl(httpClient,
                getConfiguration(), getNamespace());
            endpointsOperations.withLabels(labels);

            return (MixedOperation<Endpoints, EndpointsList, DoneableEndpoints, Resource<Endpoints, DoneableEndpoints>>) endpointsOperations
                .inAnyNamespace();
        }

        return super.endpoints();
    }
````

Like mentioned before you need to replace the .withName() calls with .withLabel("name", serviceId) which is in fact a proper replacement. (at least we've faced no issues using it so far)

**Comment by salaboy** [comment] 2018-10-01 08:46
@geoand do you know something about the release cycle for Fabric8 libs? Let's try to fix it upstream if we know that those libraries will be released frequently.

**Comment by geoand** [comment] 2018-10-01 08:49
@salaboy I am only casually involved with the upstream Fabric8 libs, but we can (and do) release them when bugs are found and fixed.
That's why I was wondering if @doernbrackandre had opened on issue there so we can track it's progress

**Comment by doernbrackandre** [comment] 2018-10-02 11:49
Hi @salaboy 
no, we did not opened an issue for that. We are fine with that workaround

**Comment by spencergibb** [comment] 2018-10-30 16:48
We're thinking that configuration properties that are opt in could work here.

**Comment by PatrickHuetter** [comment] 2019-05-16 12:12
I also think this would be a good enhancement. We also have multiple namespaces e.g. "spring-server" where services like config-server, api-gateway, spring-boot-admin or other server applications are contained. The "spring-service" namespace contains all business logic relevant services. At this time it seems that it's not possible to configure the kubernetes discovery client to obtain services from these both namespaces. Please correct me if i'm wrong.

**Comment by geoand** [comment] 2019-05-16 15:24
Isn't overriding the `KubernetesClient` bean a viable option?

**Comment by PatrickHuetter** [comment] 2019-05-20 08:40
@geoand This might be an option but i think this is some kind of basic feature many people will need in future while migrating more and more to kubernetes. So it would be nice to have some kind of configuration option for that. If you tell me in which classes i should look i could try to build such a feature and create a merge request but i have to understand many parts of the source code for now.

**Comment by geoand** [comment] 2019-05-20 08:42
I just now saw that #396 is related

**Comment by PatrickHuetter** [comment] 2019-05-20 08:59
@geoand Exactly as you described! An option would also be some kind of configuration parameter to configure something like: "all namespaces", "only selected namespaces", "one namespace", "current namespace". e.g. path.to.config.variable: namespace_1, namespace_2

I think with this feature many spring boot microservice projects that use or migrate to kubernetes will profit and make devops happy because they can configure many security policies and are very flexible.

In a first step the possibility to retrieve all namespaces would be enough because we can filter on labels afterwards to filter out some services that we don't want in service-discovery.
I've written a small article about that topic. The only thing to have a perfect setup which is missing is this feature here. https://encircle360.com/blog/2019/05/15/using-spring-boot-microservices-within-kubernetes-using-native-k8s-service-discovery-and-label-filters/

**Comment by geoand** [comment] 2019-05-20 09:02
@PatrickHuetter thanks for your feedback!

I have added a `for team discussion` label so we can go over this with the team and see what the best way to move forward might be. Just thinking about it from a high level perspective leads me to believe that is should not be too difficult, but we probably need to put some more thought into it.

**Comment by claitonp** [comment] 2019-06-09 18:22
Hi.
I am also interested in this. Would be nice to have at least the option to configure this behavior. Then, you can decide to use it or not.
any news?

**Comment by geoand** [comment] 2019-06-10 06:16
@claitonp Hi, this is still pending discussion with the team, but that should happen soon :)

**Comment by TYsewyn** [comment] 2019-09-26 12:42
@geoand I think we can close this issue since #448 has been merged?

**Comment by geoand** [comment] 2019-09-26 12:44
@TYsewyn makes sense! Go for it :)

**Comment by PatrickHuetter** [comment] 2019-09-26 12:57
I didn't have time to test it but what if the pod has now access rights to access a namespace? Does the service discovery fail or does the protected namespace get skipped after logging it and service discovery will work for the namespaces that could be retrieved? In normal sized k8s clusters you always have namespaces that are protected, for example some system namespaces or different project namespaces.

**Comment by TYsewyn** [comment] 2019-09-26 13:15
AFAIK the kubernetes client will send a `GET` request to `/api/v1/endpoints` with request parameters to retrieve all the endpoints across all namespaces. If the service account being used doesn't have access to a specific namespace then that one will be filtered out.
Those are my assumptions though, this needs to be verified.

**Comment by ryanjbaxter** [comment] 2019-10-31 14:37
Is this not addressed by https://github.com/spring-cloud/spring-cloud-kubernetes/pull/448?

**Comment by spring-issuemaster** [comment] 2019-11-07 14:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-11-14 14:41
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-11-14 14:41 UTC
Labels: enhancement, feedback-reminder, for team discussion, waiting for feedback
