### ISSUE TITLE
Health indicator should support being disabled

### ISSUE THREAD

**Issue by neonomaly** [spring-cloud/spring-cloud-kubernetes#825] opened 2021-07-08 15:24 UTC
Hi. 

There was an issue https://github.com/spring-cloud/spring-cloud-kubernetes/issues/449. 

It reproduces in spring-cloud-kubernetes-fabric8-autoconfig:2.0.3.

Hope it fill be fixed soon, thanks!

**Comment by ryanjbaxter** [comment] 2021-07-08 15:53
The conditional is still there 
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c2fd0a1f8816de943de322a1bfa39987523336f9/spring-cloud-kubernetes-client-autoconfig/src/main/java/org/springframework/cloud/kubernetes/client/KubernetesClientAutoConfiguration.java#L79

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by neonomaly** [comment] 2021-07-08 18:49
Hi. Thanks for fast response. I've made a little demo. Hope it helps.
[https://github.com/neonomaly/spring-cloud-fabric8-health-bug](https://github.com/neonomaly/spring-cloud-fabric8-health-bug)

**Comment by wind57** [comment] 2021-07-08 20:32
The annotation is still [there](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-autoconfig/src/main/java/org/springframework/cloud/kubernetes/fabric8/Fabric8AutoConfiguration.java#L131). The problem is not in the annotation, but the fact that you are using `spring-cloud-kubernetes-fabric8-config` dependency. 

This dependency has a "bootstrap configuration" [attached to it](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8BootstrapConfiguration.java), specifically it imports [Fabric8AutoConfiguration](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8BootstrapConfiguration.java#L44); as such setting the `management.health.kubernetes.enabled=false` in `application.yaml` would have no effect on that bean.

To put in other words, if you would have used `spring-cloud-kubernetes-fabric8-autoconfig`, everything would have worked (since it does not have a bootstrap step); but since you use `spring-cloud-kubernetes-fabric8-config`, this would not help. 

The solution is trivial: place your property to disable that health indicator in `bootstrap.yaml`.

To that extent, I have been looking into the documentation and this is a bit blurred. imho, we need to properly fix the documentation, which I gladly will, if Ryan agrees.

**Comment by ryanjbaxter** [comment] 2021-07-08 23:28
It seems to be a little more complicated than that.  This is only a problem when using webflux, when using `spring-boot-web` there is no need to have a bootstrap.yaml.  I suppose the workaround for now is to put in in bootstrap.yaml but I would like to understand why it is behaving differently when using webflux.

**Comment by ryanjbaxter** [comment] 2021-07-09 15:54
So the difference appears to be how the beans are fetched for the different configurations.

The non-reactive configuration fetched the beans through the application context
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.java#L81

The reactive implementation has them injected
https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/ReactiveHealthEndpointConfiguration.java#L48

I'm not sure there is much we can do from a Spring Cloud perspective to work around that.

**Comment by wind57** [comment] 2021-07-10 04:08
The problem seems to be in the way reactive and non-reactive health contributors are picked up. I'll try to explain.

When you use `org.springframework.boot:spring-boot-starter-web`, spring-boot under the hood will pick-up every instance of `HealthContributor` from the application context, as seen [in the proper configuration](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.java#L82). Specifically notice :

        applicationContext.getBeansOfType(HealthContributor.class)

In this case `@ConditionalOnEnabledHealthIndicator("kubernetes")` works

In the reactive case, they are injected directly into a method, [as seen here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/ReactiveHealthEndpointConfiguration.java#L49) and (to my surprise), that conditional does not work here.

---

Ryan made the same conclusion it seems! but much less verbose... @ryanjbaxter why wouldn't that conditional work in case of the reactive config?

**Comment by wind57** [comment] 2021-07-12 15:30
nvm. I debugged this and understood how things happen...

**Comment by ryanjbaxter** [comment] 2021-07-12 19:00
If we look at the Javadoc for `getBeansOfType` we see that it does not consider the application context hierarchy when looking for the beans.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/ListableBeanFactory.html#getBeansOfType-java.lang.Class-

Ultimately this comes down to just something we are going to have to document for now.  Fetching configuration data via the K8S API is not something we want to maintain long term so doing anything more than that at the moment seems counter productive.

**Comment by ryanjbaxter** [comment] 2021-07-12 20:40
Closed via 6dcad3a

**Closed by ryanjbaxter** 2021-07-12 20:40 UTC
Labels: documentation
