### ISSUE TITLE
Spring Boot 3.2.0 with Spring cloud 2023.0.0 | Spring Cloud API Gateway not starting on Openshift

### ISSUE THREAD

**Issue by mohitbang740** [spring-cloud/spring-cloud-kubernetes#1535] opened 2023-12-13 13:25 UTC
I have deployed spring cloud API gateway on kubernetes environment. Below are the versions which I am using

Spring Boot : 3.2.0 
Spring Cloud : 2023.0.0

While booting up the application it is stuck. I have enabled the logs at trace level and found after discovering all the services, the application is stuck. The last log I am able to see is `"RouteDefination ReactiveCompositeDiscoveryClient_{SERVICE_NAME} applying {pattern={SERVICE_NAME/**}}"`

The same code was working with Spring Cloud 2022.0.2 without any issue. After searching over the internet, I found to enable `spring.main.cloud-platform=KUBERNETES` but it doesn't helped at all.

According to the breaking changes of 2022.0.3 [RELEASE_NOTES](https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2022.0-Release-Notes) changes has been made in Spring Cloud Kubernetes component.

Can any one help with the configuration which is needed to be done to make it work.

I have enabled the property `spring.main.cloud-platform=KUBERNETES` and still the issue is persisting.

Expecting to boot up the API Gateway with all the service discovery.

**Comment by ryanjbaxter** [comment] 2023-12-13 13:35
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by mohitbang740** [comment] 2023-12-13 17:07
It is just vanilla with spring boot and spring cloud without any code. It has below dependencies which are managed by the BOM

- spring-cloud-starter-gateway
- spring-cloud-kubernetes-client-all
- spring-boot-starter-actuator
- spring-cloud-starter-loadbalancer

The catch here is, the same piece of application works fine in my local machine but it doesn't get boot up in Openshift.

Below are the configs which are added in application.yaml
```
spring:
  cloud:
    kubernetes:
      enabled: true
    gateway:
      enabled: true
      discovery.locator.enabled: true
      discovery.locator.lower-case-service-id: true
```

Let me know if any thing else is needed, as the machine where the application lies won't allow to upload any piece of code. If needed we can have a discussion on this.

**Comment by ryanjbaxter** [comment] 2023-12-13 22:41
It would still be helpful to provide the exact code to reproduce the problem so we can try and replicate it.  Have you tried this on a vanilla k8s cluster?

**Comment by mohitbang740** [comment] 2023-12-20 08:53
I created a pure vanilla application with spring cloud gateway and it worked fine for me. 
To deep dive into the issue, I tried by adding the library and configuration which we had in our gateway application.
I found the issue occur when I enable the **FeignClients** with `@EnableFeignClients` annotation at that time the system is not starting up.

Are you aware about the configuration that need to be done here?

**Comment by ryanjbaxter** [comment] 2023-12-20 11:47
That shouldn’t require any extra configuration that I’m aware of

**Comment by ryanjbaxter** [comment] 2023-12-20 19:54
I am not sure how you are combining OpenFeign and the Gateway, but no they are not compatible.  OpenFeign is blocking and the Gateway needs is non-blocking.

**Comment by mohitbang740** [comment] 2023-12-22 09:24
So this can be the reason that application not started?
But the same application started in my local, any idea what can be done?

**Comment by ryanjbaxter** [comment] 2023-12-22 10:16
Doesn’t sound like it but it’s impossible for me to tell since I don’t have anything to reproduce the problem with

**Comment by spring-cloud-issues** [comment] 2023-12-29 10:19
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-01-05 10:19
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-01-05 10:19 UTC
Labels: feedback-reminder
