### ISSUE TITLE
Disabling "kubernetes" InfoContributor does not work

### ISSUE THREAD

**Issue by UltimateFighter** [spring-cloud/spring-cloud-kubernetes#955] opened 2022-01-14 08:49 UTC
As described here, you should be able to disable the Info Contributor for kubernetes in application.yaml as follows.

https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#info-contributor

``` 
management:
   info:
      kubernetes:
        enabled: false
``` 

Unfortunately this does not work and the kubernetes infos still appear under the actuator endpoint "/info".

I used the following dependency:
``` 
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes</artifactId>
    <version>1.1.10.RELEASE</version>
</dependency>
```

**Comment by UltimateFighter** [comment] 2022-01-14 12:38
This is the relevant section from the application.yaml

``` 
management:
  endpoints:
    web:
      base-path: /manager
      exposure:
        include: 'health,info'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    kubernetes:
      enabled: false
```

**Comment by ryanjbaxter** [comment] 2022-01-14 13:03
Can you try using spring cloud 2020.0.4?

**Comment by UltimateFighter** [comment] 2022-01-14 14:54
It's the same unexpected result ... "kubernetes" is still visible

**Comment by wind57** [comment] 2022-01-16 11:39
We need more details. With `spring cloud 2020.0.4` what exact dependencies are you using? because that is just a `pom` file. May be share the `pom.xml` or even better a simple, reproducible project on github. 

My point is that the info contributors are present in autoconfigure projects, either `spring-cloud-kubernetes-client-autoconfigure` or `spring-cloud-kubernetes-fabric8-autoconfigure`... and currently I don't have a good understanding of your project to make an accurate statement if this is a bug or not. 

May be to help you out a bit I've put up this example [here](https://github.com/wind57/spring-cloud-k8s-it/tree/main/issue-955), where I can't reproduce your issue _within the set-up of that project_, obviously. If you could play with that a little and show me how to reproduce your issue, that would be very helpful. Thank you upfront.

**Comment by UltimateFighter** [comment] 2022-01-17 10:16
Hello, i can reproduce the problem b using this changes in your example project:

```
ext {
    ...
    set('springBootVersion', "2.5.4")
}
...
dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter'
    implementation 'org.springframework.cloud:spring-cloud-starter-kubernetes-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-kubernetes-config:1.1.8.RELEASE'
    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
    implementation "org.springframework.boot:spring-boot-starter:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-actuator:${springBootVersion}"
}
...
```

!We use a bootstrap.yml in our application!

**Comment by wind57** [comment] 2022-01-17 10:26
what does "!We use a bootstrap.yml in our application!" mean? Didn't you say in the very first post?

> As described here, you should be able to disable the Info Contributor for kubernetes in application.yaml as follows.

Even better - wanna create a PR in that tiny project that reproduces the problem? thank you

**Comment by UltimateFighter** [comment] 2022-01-17 11:39
Ok, I have created a PR. Inside the PR the config is set to "management.info.kubernetes.enabled = false", but the kubernetes part is visible under "localhost:8080/manager/info". I didn't have the bootstrap in focus before. I suspect that it is because of the dependency "org.springframework.cloud:spring-cloud-starter-bootstrap" possibly in connection with "org.springframework.cloud:spring-cloud-starter-kubernetes-config".

https://github.com/wind57/spring-cloud-k8s-it/pull/4

**Comment by wind57** [comment] 2022-01-17 13:41
It seems that the issue you are having was resolved [here](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/825). Darn, I even contributor with a PR there, I have one short memory... :)

When we said to try with `2020.0.4`, we really meant this:

```
dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-kubernetes-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
    implementation "org.springframework.boot:spring-boot-starter"
}
```

and 

```
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
```

This should work. Can you give a try?

**Comment by ryanjbaxter** [comment] 2022-01-17 17:03
Yes please use the BOM (2020.0.x) to pull in the correct dependencies.  If you upgrade it should work.

**Comment by wind57** [comment] 2022-01-22 14:23
@UltimateFighter if things worked for you, would you mind closing this issue?

**Comment by UltimateFighter** [comment] 2022-01-22 14:35
If i added the bootstrap support, i can only included the configuration in the bootstrap.yaml and the application.yaml entries are ignored. If this is the expected behavior, the issue can be close.

**Comment by ryanjbaxter** [comment] 2022-01-22 14:39
It might be true for some properties but shouldnt be true for all properties

**Comment by wind57** [comment] 2022-01-22 14:40
Did you upgrade, the way we told you to? If you are talking about the dependencies _with_ the starter that you initially reported, then yes, bootstrap.yaml is the only way to disable it. If you upgrade to use that bom _only_, the you do not need boostrap. Makes sense?

**Comment by wind57** [comment] 2022-05-04 19:20
imho, this issue can be closed. We explained what to do and how to work around this + this has already been fixed in main... @ryanjbaxter wdyt?

**Closed** 2022-05-04 19:57 UTC
Labels: feedback-provided
