### ISSUE TITLE
reload configmap

### ISSUE THREAD

**Issue by damon008** [spring-cloud/spring-cloud-kubernetes#506] opened 2019-12-23 07:35 UTC
**Describe the bug**
Using examples, I wrote one,but I found the app not reload configmap after execute 'kubectl edit cm demo-configmap', Then I delete the pod of app, it can get the latest config

**Sample**
my bootstrap.yaml
![image](https://user-images.githubusercontent.com/25023599/71343203-08242800-259a-11ea-82d2-b31ecd3df685.png)

**Comment by lubumbax** [comment] 2019-12-23 14:19
@damon008 , can you try naming your ConfigMap the same as the spring application?. Something like:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-admin
  namespace: your-namespace
```

The `management.endpoint.restart.enabled: "true"` property is not really mandatory, at least in the latest releases. 

Adding to that, I have been able to make that work on `Greenwich.SR4` (and SR1, SR2, SR3).  
```
        <spring-boot.version>2.1.8.RELEASE</spring-boot.version>
        <spring-cloud.version>Greenwich.SR4</spring-cloud.version>
        <spring.cloud.k8s.version>1.1.1.RELEASE</spring.cloud.k8s.version>
```
Unfortunately, if I change to `Hoxton.SR1` the changes in a ConfigMap won't be reloaded anymore.

**Comment by damon008** [comment] 2019-12-24 01:28
@lubumbax I add application.yaml for mybatis and server port and so on in my project.Does it have any influence?

**Comment by damon008** [comment] 2019-12-24 03:31
what is the views of the official spring?

**Comment by damon008** [comment] 2019-12-24 05:46
@lubumbax  do what you  said, the app run failed, 
show the log:
![image](https://user-images.githubusercontent.com/25023599/71396083-a3c59f00-2653-11ea-8025-3b1a8e0fb755.png)

**Comment by lubumbax** [comment] 2019-12-24 10:56
> @lubumbax I add application.yaml for mybatis and server port and so on in my project.Does it have any influence?

Not sure what "mybatis" means.  
Combining an `application.yaml` with `ConfigMap` is fine. You can also add a `bootstrap.yaml` to that if you want. You can add properties to either of them.  
I prefer (like many others) adding all possible app/service properties to `ConfigMap` and only those that are most critical for the app to start to `bootstrap.yaml`. That said, I would get rid of `application.yaml` and put as much as possible in `ConfigMap`.

The views of the official spring are well documented here:
https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.1.RELEASE/reference/html/#kubernetes-propertysource-implementations
My advise is that you make a thorough read of that chapter and see if something rings a bell.

A bit more about `application.yaml` vs `bootstrap.yaml` [here](https://stackoverflow.com/questions/32997352/what-is-the-difference-between-putting-a-property-on-application-yml-or-bootstra).

Regarding the last screenshot, I can't really say what causes that exception. What dependencies have you added to your POM (assuming you are using Maven)?

**Comment by damon008** [comment] 2019-12-25 02:51
@lubumbax 
it print log when I edit cm configmap-name，it show me that it reload
![image](https://user-images.githubusercontent.com/25023599/71429842-b1d2f880-2703-11ea-9b4e-60e74ea580f7.png)
The following levels of reload are supported (by setting the spring.cloud.kubernetes.reload.strategy property): * refresh (default): Only configuration beans annotated with @ConfigurationProperties or @RefreshScope are reloaded.
I use @ConfigurationProperties ，but I can not get the new value from the configmap of what I edit.

**Comment by damon008** [comment] 2019-12-25 03:13
@lubumbax  Can you show your demo?

**Comment by damon008** [comment] 2019-12-27 08:24
@lubumbax
Hello, I found what happened.After add db such as mybatis or redis when use the springcloud-kubernetes with configmap, the configmap can not be reloaded.


you can try when add db resource such as redis or mysql.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lubumbax"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 晚上6:56
收件人:&nbsp;"spring-cloud/spring-cloud-kubernetes"<spring-cloud-kubernetes@noreply.github.com&gt;;
抄送:&nbsp;"530840587"<530840587@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-cloud/spring-cloud-kubernetes] reload configmap (#506)



 
@lubumbax I add application.yaml for mybatis and server port and so on in my project.Does it have any influence?
  
Not sure what "mybatis" means.
 Combining an application.yaml with ConfigMap is fine. You can also add a bootstrap.yaml to that if you want. You can add properties to either of them.
 I prefer (like many others) adding all possible app/service properties to ConfigMap and only those that are most critical for the app to start to bootstrap.yaml. That said, I would get rid of application.yaml and put as much as possible in ConfigMap.
 
The views of the official spring are well documented here:
 https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.1.RELEASE/reference/html/#kubernetes-propertysource-implementations
 My advise is that you make a thorough read of that chapter and see if something rings a bell.
 
A bit more about application.yaml vs bootstrap.yaml here.
 
Regarding the last screenshot, I can't really say what causes that exception. What dependencies have you added to your POM (assuming you are using Maven)?

**Comment by damon008** [comment] 2020-01-02 11:07
@lubumbax   Do you have a similar problem?

**Comment by lubumbax** [comment] 2020-01-02 13:49
Not really. I added the following dependencies to one of my services:
```
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.9.0</version>
            <type>jar</type>
        </dependency>
```
Then configured a `JedisConnectionFactory` bean that connected to Redis running on another service. 

A change in the ConfigMap of that service triggered reload.

**Comment by damon008** [comment] 2020-01-03 01:56
@lubumbax  What kind of your JedisConnectionFactory? and about mysql , what kind of mybatis? about the bean

**Comment by damon008** [comment] 2020-01-03 01:59
you can try this:
```
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-redis</artifactId>
			<version>1.4.7.RELEASE</version>
		</dependency>
```
In my project, this can not

**Comment by damon008** [comment] 2020-01-03 02:40
I try what uou said, I found it not reload before delete pod

**Comment by lubumbax** [comment] 2020-01-03 12:16
I would need to get a link to a code repo with a sample application reproducing the issue; please provide it here.

**Comment by damon008** [comment] 2020-01-04 01:42
@lubumbax  

the demo code:
Base on 
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.8.RELEASE</version>
        <relativePath/>
    </parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<swagger.version>2.6.1</swagger.version>
		<xstream.version>1.4.7</xstream.version>
		<pageHelper.version>4.1.6</pageHelper.version>
		<fastjson.version>1.2.51</fastjson.version>
		<shiro.version>1.3.0</shiro.version>
		<!-- <kubernetes-client-version>6.0.1</kubernetes-client-version> -->
		<kubernetes-client-version>5.0.0</kubernetes-client-version>
		<fabric8-kubernetes-client.version>4.6.1</fabric8-kubernetes-client.version><!-- 对应k8s v1.15.3 -->
		<springcloud.version>Greenwich.SR4</springcloud.version>
		<springcloud.kubernetes.version>1.1.1.RELEASE</springcloud.kubernetes.version>
		<mysql.version>5.1.46</mysql.version>
	</properties>
```
redis :
```
<dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <type>jar</type>
        </dependency>
```

redis bean:
```
@Configuration
@EnableCaching
public class RedisCacheConfig extends CachingConfigurerSupport {
    private Logger logger = LoggerFactory.getLogger(RedisCacheConfig.class);
    
    private static JedisPool jedisPool;
    
    @Autowired
    private EnvConfig envConfig;
    
    /**
     * redis连接工厂
     */
    @Bean
    public JedisPool redisPoolFactory() {
        logger.info("redis url: " + envConfig.getSpring_redis_host() + ":" + envConfig.getSpring_redis_port());
        JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
        jedisPoolConfig.setMaxIdle(8);
        jedisPoolConfig.setMaxWaitMillis(10000);
        if(StringUtils.isBlank(envConfig.getSpring_redis_pwd())) {
        	 jedisPool = new JedisPool(jedisPoolConfig, envConfig.getSpring_redis_host(), Integer.parseInt(envConfig.getSpring_redis_port()), 10000);
        } else {
        	 jedisPool = new JedisPool(jedisPoolConfig, envConfig.getSpring_redis_host(), Integer.parseInt(envConfig.getSpring_redis_port()), 10000, envConfig.getSpring_redis_pwd());
        }
        return jedisPool;
    }

    public JedisPool getJedisPool(){
    	if(null == jedisPool){
    		redisPoolFactory();
    	}
    	return jedisPool;
    }
```


demo:

```
        @Autowired
	private RedisCacheConfig redisCacheConfig;

	@GetMapping(value = "/getTest")
	public String getTest() {
		Jedis jedis = null;
		try {
			JedisPool jedisPool = redisCacheConfig.getJedisPool();
			jedis = jedisPool.getResource();
			return envConfig.getBase_path();
		} 
		catch (JedisException e) {
			logger.error("get redisResource failed", e);
		}
		catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		finally {
			if (jedis != null) {
				jedis.close();
			}
		}
		return null;
	}
```
In EnvConfig, the value of base_path can not reload after edit cm

**Comment by damon008** [comment] 2020-01-04 01:46
@lubumbax 
Can you show your demo code?

**Comment by damon008** [comment] 2020-01-04 01:56
@lubumbax 
I care what kind of your pom?

**Comment by damon008** [comment] 2020-01-04 03:37
After I edit cm, the log show it change and refresh.
![image](https://user-images.githubusercontent.com/25023599/71759278-bb1f4a80-2ee5-11ea-88f3-75974a7e3e74.png)

but I cannot get the edited value with redis or mybatis (mysql), and if I remove db or some pertinent dependence of db (redis). or ``` I means if use db or redis in the project, it also can not reload the newest value after edited the configmap,but if without db or redis, it can```

**Comment by geoand** [comment] 2020-01-06 10:46
I am sorry but I don't really know why redis or mysql configuration would not be reloaded after a config change

**Comment by damon008** [comment] 2020-01-07 04:27
@lubumbax  Can you show your all demo with redis or mysql?

**Comment by Haybu** [comment] 2020-03-06 20:47
would you please give this spin with version 1.1.3.BUILD-SNAPSHOT and report back your findings

**Comment by spring-issuemaster** [comment] 2020-03-13 20:49
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-03-20 20:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-03-20 20:49 UTC
Labels: feedback-reminder, waiting for feedback
