### ISSUE TITLE
KubernetesCatalogWatch is missing in spring-cloud-kubernetes-client-discovery

### ISSUE THREAD

**Issue by hammadirshad** [spring-cloud/spring-cloud-kubernetes#745] opened 2021-02-23 22:36 UTC
**Describe the bug**
spring-cloud-starter-kubernetes  version **1.1.8.RELEASE**
**[KubernetesCatalogWatch](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/1.1.x/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesCatalogWatch.java)** was exist is **spring-cloud-kubernetes-discovery** module.

but after update to **2.0.1**

 **[KubernetesCatalogWatch](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/KubernetesCatalogWatch.java)**  is exists in **spring-cloud-kubernetes-fabric8-discovery**  module but it is missing in  **spring-cloud-kubernetes-client-discovery** module

**Comment by ryanjbaxter** [comment] 2021-02-24 14:41
You are right, looks like we are missing this feature for parity.

**Comment by wind57** [comment] 2022-11-20 19:30
@ryanjbaxter duplicate of [this](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1042). Can we close this one? My next todo is to fix that issue. thank you

**Comment by ryanjbaxter** [comment] 2022-11-22 01:38
Closing in favor of https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1042

**Closed by ryanjbaxter** 2022-11-22 01:38 UTC
Labels: bug
