### ISSUE TITLE
Kubernetes Configuration Watcher failed to connect and stopped watching for changes

### ISSUE THREAD

**Issue by brachipa** [spring-cloud/spring-cloud-kubernetes#645] opened 2020-09-26 18:02 UTC
We are using [watcher pod](https://github.com/spring-cloud/spring-cloud-kubernetes#12-spring-cloud-kubernetes-configuration-watcher) to watch on secret/configmap changes.
From time to time it raises connection errors and watcher pod stopped watch for changes, it didn't try even to reconnect.

samples errors :
* Connection reset at java.net.SocketInputStream.read(SocketInputStream.java:210) 
* java.net.ConnectException: Failed to connect to /***:443 at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
*java.io.EOFException: null at okio.RealBufferedSource.require(RealBufferedSource.java:65)

And always we see `WatchConnectionManager : Exec Failure`

Currently I monitor errors in the watcher and restart the watcher when received errors, but we must get a normal solution.
Any idea how can it be fixed? or even workaround? code changes? can I catch this errors and trigger a reconnect?

**Comment by ryanjbaxter** [comment] 2020-10-19 15:26
Can you please provide a sample?  I think you might have pointed to the wrong documentation above.  Is this not the same issue? https://github.com/spring-cloud/spring-cloud-kubernetes/pull/570

**Comment by spring-issuemaster** [comment] 2020-10-26 15:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-11-02 15:28
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-11-02 15:28 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by dmitrypotenko** [comment] 2022-07-14 12:59
The issue is still relevant. Seems like watcher stops reacting on configmap changes a after connection reset.

> 2022-07-14 12:23:48.837 WARN 1 --- [://10.0.0.1/...] i.f.k.c.d.i.WatcherWebSocketListener : Exec Failure javax.net.ssl.SSLException Connection reset
2022-07-14 12:23:48.840 ERROR 1 --- [://10.0.0.1/...] .w.HttpBasedConfigMapWatchChangeDetector : Error while establishing a connection to watch config maps: configuration may remain stale
io.fabric8.kubernetes.client.KubernetesClientException: Failed to start websocket
at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onFailure(WatcherWebSocketListener.java:77) ~[kubernetes-client-5.10.2.jar:na]
at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.ws.RealWebSocket$1.onFailure(RealWebSocket.java:216) ~[okhttp-3.14.9.jar:na]
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:180) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.14.9.jar:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_332]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_332]
at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_332]
Suppressed: java.lang.Throwable: waiting here
at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:164) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:175) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.waitUntilReady(WatcherWebSocketListener.java:120) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:80) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:579) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:554) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:91) ~[kubernetes-client-5.10.2.jar:na]
at org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector.watch(EventBasedConfigMapChangeDetector.java:81) ~[spring-cloud-kubernetes-fabric8-config-2.1.3.jar:2.1.3]
at org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector$1.lambda$onClose$2(EventBasedConfigMapChangeDetector.java:97) [spring-cloud-kubernetes-fabric8-config-2.1.3.jar:2.1.3]
at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_332]
at org.springframework.cloud.kubernetes.fabric8.config.reload.EventBasedConfigMapChangeDetector$1.onClose(EventBasedConfigMapChangeDetector.java:97) [spring-cloud-kubernetes-fabric8-config-2.1.3.jar:2.1.3]
at io.fabric8.kubernetes.client.utils.WatcherToggle.onClose(WatcherToggle.java:56) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.close(AbstractWatchManager.java:95) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onStatus(AbstractWatchManager.java:273) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:257) ~[kubernetes-client-5.10.2.jar:na]
at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93) ~[kubernetes-client-5.10.2.jar:na]
at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209) ~[okhttp-3.14.9.jar:na]
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[okhttp-3.14.9.jar:na]
... 4 common frames omitted
Caused by: javax.net.ssl.SSLException: Connection reset
at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[na:1.8.0_332]
at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[na:1.8.0_332]
at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[na:1.8.0_332]
at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[na:1.8.0_332]
at sun.security.ssl.SSLTransport.decode(SSLTransport.java:138) ~[na:1.8.0_332]
at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397) ~[na:1.8.0_332]
at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305) ~[na:1.8.0_332]
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440) ~[na:1.8.0_332]
at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133) ~[kubernetes-client-5.10.2.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:38) ~[kubernetes-client-5.10.2.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[kubernetes-client-5.10.2.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:309) ~[kubernetes-client-5.10.2.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:na]
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172) ~[okhttp-3.14.9.jar:na]
... 4 common frames omitted
Suppressed: java.net.SocketException: Broken pipe (Write failed)
at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_332]
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_332]
at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_332]
at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81) ~[na:1.8.0_332]
at sun.security.ssl.TransportContext.fatal(TransportContext.java:355) ~[na:1.8.0_332]
... 42 common frames omitted
Caused by: java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_332]
at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_332]
at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464) ~[na:1.8.0_332]
at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165) ~[na:1.8.0_332]
at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109) ~[na:1.8.0_332]
... 39 common frames omitted

**Comment by ryanjbaxter** [comment] 2022-07-14 14:01
This seems a bit different in nature.  Seems like the Kubernetes API server might be using an untrusted SSL certificate.

**Comment by dmitrypotenko** [comment] 2022-07-18 19:28
That is odd, because it works for some time and only then fails fatally. While the cause of connection reset surely might be different, the consequence is the same - watcher stops tracking changes after a connection reset.

**Comment by wind57** [comment] 2022-07-18 19:40
I wonder if this will still happen in `3.0.x` ( when its going to be released), since we dropped watchers in favor of informers. While making this change to informers, I did play around to let the application idle for ( up to two hours ) and then change a configmap, and I still received proper events.

Informers are supposed to be more resilient, so it will be interesting to see.

**Comment by ryanjbaxter** [comment] 2022-07-26 00:10
@dmitrypotenko what version are you using?

**Comment by dmitrypotenko** [comment] 2022-07-26 14:52
2.1.3

**Comment by ryanjbaxter** [comment] 2022-07-26 19:17
Do you have a way to reliably reproduce the issue?

**Comment by dmitrypotenko** [comment] 2022-08-12 09:07
@ryanjbaxter Unfortunately no, I have not yet tried to reproduce it.

**Comment by ryanjbaxter** [comment] 2022-08-12 09:25
Once you have a reliable way of reproducing the problem let me know and I will take a look

**Comment by dmitrypotenko** [comment] 2022-09-01 12:51
As far as I can see you are moving away from fabric8 client so I think the better approach is to test watcher with kubernetes official client and see if issue is gone. (And I could not reproduce the issue locally  😄)
