### ISSUE TITLE
OpenFeign+SpringCloud-Kubernetes

### ISSUE THREAD

**Issue by Taogang00** [spring-cloud/spring-cloud-kubernetes#722] opened 2021-01-21 03:20 UTC
**Describe the bug**
**1.Env:**
Spring Cloud version: Hoxton.SR9
SpringBoot 2.3.7.RELEASE

This is my k8s information
![image](https://user-images.githubusercontent.com/19925601/105274773-db957200-5bd8-11eb-91f4-5de95479dfcb.png)

I wrote a test project, I want to access the service on k8s through feign+springcloud kubernetes：

**1.feign client:**
@FeignClient(value = "guanwei-cloud-service-account-at-service", fallback = AccountClient.AccountClientImpl.class)
public interface AccountClient {

    @GetMapping("/api/account/qts")
    String get();

    @Service
    class AccountClientImpl implements AccountClient {
        @Override
        public String get() {
            return null;
        }
    }
}

**2.controller:**
@RestController
@RequestMapping("/api/test")
public class TestController { 

    @Autowired
    private AccountClient accountClient;
    
    @GetMapping("1")
    String qts() {
        return accountClient.get();
    }   
}

**3.application.properties:**

spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.kubernetes.discovery.all-namespaces=true
spring.cloud.kubernetes.loadbalancer.enabled=true
spring.cloud.kubernetes.client.ca-cert-file=E:\\gitee\\guanwei-cloud\\guanwei-cloud-service-test\\src\\main\\resources\\ca.crt
spring.cloud.kubernetes.client.master-url=https://192.168.2.105:6443

4.k8s all service:
![image](https://user-images.githubusercontent.com/19925601/105275187-b2c1ac80-5bd9-11eb-911b-e3629ec3173d.png)

5.when i call interface: http://localhost:8805/api/test/1，**stack info:**
 
[2021-01-21 11:15:17.204][WARN][Thread:[boundedElastic-1]][org.springframework.cloud.loadbalancer.core.RoundRobinLoadBalancer][getInstanceResponse line:128][No servers available for service: guanwei-cloud-service-account-at-service]
[2021-01-21 11:15:17.204][WARN][Thread:[http-nio-8805-exec-1]][org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient][execute line:67][Load balancer does not contain an instance for the service guanwei-cloud-service-account-at-service]
[2021-01-21 11:15:17.212][ERROR][Thread:[http-nio-8805-exec-1]][org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]][log line:175][Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is feign.FeignException$ServiceUnavailable: [503] during [GET] to [http://guanwei-cloud-service-account-at-service/api/account/qts] [AccountClient#get()]: [Load balancer does not contain an instance for the service guanwei-cloud-service-account-at-service]] with root cause]
feign.FeignException$ServiceUnavailable: [503] during [GET] to [http://guanwei-cloud-service-account-at-service/api/account/qts] [AccountClient#get()]: [Load balancer does not contain an instance for the service guanwei-cloud-service-account-at-service]
	at feign.FeignException.serverErrorStatus(FeignException.java:237)
	at feign.FeignException.errorStatus(FeignException.java:180)
	at feign.FeignException.errorStatus(FeignException.java:169)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92)
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy91.get(Unknown Source)
	at com.guanwei.test.TestController.qts(TestController.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

expecting reply！oo

**Comment by ryanjbaxter** [comment] 2021-01-21 15:17
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by Taogang00** [comment] 2021-01-22 02:59
Thank you for answer, my case: https://github.com/Taogang00/guanwei-cloud-service-test/tree/1.x  Maybe you need to modify some config:  spring.cloud.kubernetes.client.master-url, @FeignClient(value = "xx")

**Comment by ryanjbaxter** [comment] 2021-01-22 16:22
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/723#issuecomment-765523229

**Comment by spring-cloud-issues** [comment] 2021-01-29 16:27
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-02-05 16:26
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-02-05 16:26 UTC
Labels: feedback-reminder, waiting for feedback
