### ISSUE TITLE
There is no way to get pod metadata

### ISSUE THREAD

**Issue by vamsikrishnanekkalapudi** [spring-cloud/spring-cloud-kubernetes#496] opened 2019-12-05 13:31 UTC
I would like to get the meta data of a pod but i could not able to found the way to do it.

The way we are getting the service metadata as below in the similar way i would like to get the meta data of a pod.
```
ServiceInstance serviceInstance=..
serviceInstance.getMetadata();//it's giving the service metadata.
```
Is there any way to do it?

**Comment by ryanjbaxter** [comment] 2019-12-09 15:31
Right we do not expose each Pods metadata.  There would likely be a big performance impact of doing so.

**Comment by vamsikrishnanekkalapudi** [comment] 2019-12-10 05:41
Thanks for your response.
But we have a use case where we need to assign a job to appropriate pod based on the labels of the pod.
Can we achieve this by using io.fabric8.kubernetes.client.KubernetesClient object?

**Comment by ryanjbaxter** [comment] 2020-04-01 14:37
Actually this should happen by default


spring.cloud.kubernetes.discovery.metadata.add-labels | true | When set, the Kubernetes labels of the services will be included as metadata of the returned ServiceInstance.
-- | -- | --

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2020-04-08 14:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-04-15 14:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-04-15 14:40 UTC
Labels: feedback-reminder, waiting for feedback
