### ISSUE TITLE
Upgrading to Spring Boot 3, config does not load - Cannot enhance @Configuration KubernetesClientAutoConfiguration

### ISSUE THREAD

**Issue by codex70** [spring-cloud/spring-cloud-kubernetes#1169] opened 2022-12-09 06:04 UTC
**Describe the bug**
I'm upgrading an existing project to spring boot 3 and using the spring-cloud-kubernetes-3.0.0-RC3 dependency.

When I start the application it is no longer loading the configuration and I get the following error message:
```
Cannot enhance @Configuration bean definition 'org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
```

**Sample**
The is the configuration I am using:
```
spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
        all-namespaces: true # Servlet container configuration
      reload:
        period: 1000
        enabled: true
        mode: event
      config:
        enabled: true
        name: test-service
        sources:
          - name: test-service
```

Not sure what other code would be useful to supply, I really don't know where to start with this. Spent the past few days googling, and I'm sure I'm missing something obvious.

**Comment by wind57** [comment] 2022-12-09 06:38
Can you create a git repo with all the needed details? I mean, a real maven/gradle project and instructions on how to build and deploy it. If you do, I will gladely take a look.

**Comment by codex70** [comment] 2022-12-09 07:10
Thanks, I will try to see if I can create a project that replicates the issue. Unfortunately I cannot share the current source code, but can probably create a stripped down version.

**Comment by codex70** [comment] 2022-12-09 14:58
OK, I've got a fairly clean repository setup that I believe is still causing the problem (at least it is in my cluster).

https://github.com/codex70/spring-boot-service

There's the application code, which requires java 17+ and gradle 7.6. I've also included a helm chart which I use to deploy the application. Hopefully it will all still work and give you an idea of where I'm seeing problems.

**Comment by codex70** [comment] 2022-12-09 15:21
Also, an interesting note, I am able to configure the application using json stored in a ConfigMap and passing the following  environment value:
```
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev,kubernetes
    - name: SPRING_APPLICATION_JSON
      valueFrom:
        configMapKeyRef:
          name: spring-config
          key: application.json

```

**Comment by codex70** [comment] 2022-12-11 08:49
@wind57,,the app starts without problem, it just doesn't load the ConfigMap so no configuration variables are loaded. This is a bit of a blocker as we use a CICD pipeline which inserts secrets using the helm template. There are work arounds, but they are nowhere near as nice.

**Comment by codex70** [comment] 2022-12-11 08:51
There are no errors when starting the application to show why the ConfigMap is not loaded, the only thing  can see is the above message which might explain why it's not working. The CM does load correctly with spring boot 2.x

**Comment by wind57** [comment] 2022-12-11 09:04
I am really confused what the problem is then, because your first post in this issue says something to do with `reload`, but now something to do with a configmap.

So what exactly are you trying to achieve (again, please make it as simple as possible :) ) and what is the problem? You have an app that is trying to read from a ConfigMap for its properties?

**Comment by codex70** [comment] 2022-12-11 09:08
Hi thanks @wind57, there was nothing specific about reload,

What I am trying to achieve is loading a PropertySource using a configmap:
https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#kubernetes-propertysource-implementations

**Comment by codex70** [comment] 2022-12-11 09:11
In my code, there is a helm template: `application.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}
  labels:
    version: {{ .Values.applicationYaml.info.app.version }}
    app: {{ .Values.application.name }}
data:
{{- with .Values.applicationYaml }}
  application.yml: |-
{{ toYaml . | indent 4 }}
{{- end }}
```

which should load the following application.yaml:
```
applicationYaml:
  spring:
    cloud:
      kubernetes:
        discovery:
          enabled: "true"
  server:
    ssl:
      enabled: false
  info:
    app:
      version: 1.0.0
```
but this doesn't work for me.

**Comment by wind57** [comment] 2022-12-11 09:12
Excellent. Then please provide a simple reproducible example, strip down helm, strip down security, everything that is not essential. This should be very simple: an app, a deployment, a configmap; steps to reproduce.

**Comment by codex70** [comment] 2022-12-11 09:13
OK, will work on it and let you know.

**Comment by codex70** [comment] 2022-12-12 09:51
Hi @wind57, I've now stripped down the application, I think it's now as minimal as it can be.

I've also deleted the helm charts and created a directory with a deployment and a configmap file, together with a service account, in case it is needed. I haven't added roles and role binding to keep it simple.

In my setup I'm still seeing the same issue, the configmap is not being read and the application is deployed on the default port of 8080, not the port 8088 provided in the ConfigMap:
```
2022-12-12T09:27:17.996Z  INFO 1 --- [           main] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2022-12-12T09:27:18.135Z  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=2134b040-c28c-38d8-97d1-e0dd2c9590e9
2022-12-12T09:27:18.408Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-12-12T09:27:18.416Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2
```

**Comment by wind57** [comment] 2022-12-13 12:50
First things first: thank you for making a reproducible example. This has triggered two issues on our side, one small, one bigger. 

The "bigger" has to do with logging. The way we have logging currently implemented, you can't really see what is going on. We will fix this relatively soon.

Now to your issue at hand: 

I think that you are confusing `application.yaml` and `bootstrap.yaml` to begin with.
In your sample you define your sources in `application.yaml` and that is not correct - that is not going to work. You need to put them in `bootstrap.yaml` + enable bootstraping. You might want to take a look at the [updated documentation](https://docs.spring.io/spring-cloud-kubernetes/docs/3.0.0-RC3/reference/html/#kubernetes-propertysource-implementations)

If you read carefully that documentation and conform to it, you can indeed put your settings in `application.yaml` (since your app name is the same as the configmap name), here is a slightly simpler version (notice that I've dropped a few things from your initial one):

```
spring:
  config:
    import: "kubernetes:"
  application:
    name: spring-boot-service

server:
  ssl:
    enabled: false
  port: 8080

```

But if you run this, "nothing" will happen. Actually nothing will be visible to you in logs (because of that problem of ours with logging), in reality though (this is what you should see and will once we fix the issue with logging):

```
2022-12-13T12:37:51.881Z  WARN 1 --- [           main] o.s.c.k.commons.config.ConfigUtils       : {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:spring-boot:sp
ring-boot-service\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"spring-boot\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}
. Ignoring.

java.lang.RuntimeException: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:spring-boot:spring-boot-service\" cannot list resource \"configmaps\" in API group \
"\" in the namespace \"spring-boot\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}
```

---

If I configure correct RBAC:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
```

and 


```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: spring-cloud-kubernetes-core-k8s-client-it
  name: spring-cloud-kubernetes-role-binding
  namespace: spring-boot
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-role
subjects:
  - kind: ServiceAccount
    name: spring-boot-service
    namespace: spring-boot
```

deploy again and will see:

```
2022-12-13T12:48:42.073Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8088 (http)
```

**Comment by codex70** [comment] 2022-12-13 12:55
Thank you so much for taking the time to look into this. I will implement this today and let you know how I get on.

**Comment by codex70** [comment] 2022-12-13 15:09
This now works as expected, thank you so much for you time on this.

I do have one question, in the "real" application I have a profile called "kubernetes" with the appropriate "application-kubernetes.yml" which contains the settings for running the application in kubernetes (including the cloud kubernetes config). This allows me to keep the kubernetes setup out of the main application.yml file.

When it loads the "spring-boot-service" ConfigMap inside kubernetes, it looks to completely replace the kubernetes profile, is this the expected behaviour? I was expecting the configuration to be the sum of the profile and the ConfigMap, not the ConfigMap totally replacing the profile. 

Obviously this isn't a big deal, just want to understand what is happening.

**Comment by wind57** [comment] 2022-12-13 15:38
>  I was expecting the configuration to be the sum of the profile and the ConfigMap

Me too, actually.

1. Are you using the new config-data api, i.e.:

```
spring:
  config:
    import: "kubernetes:"
```

2. Are both configmaps having a single property `application.yaml`?

---

From what I see in the code that should not happen, and if you say it does - you now the drill already, I am going to need a reproducible example. In the meanwhile, I am going to check if we have a test covering such a case. 

Either way, I would suggest you open a new defect and we start talking over there, as its an entirely different thing. Also, please don't close this one yourself, until we fix the code. thank you.

**Comment by wind57** [comment] 2022-12-13 16:13
we did not had such a test case per-se, so I added one : https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1175/files

So unless you can provide a reproducible example, I can't really help you...

**Comment by codex70** [comment] 2022-12-13 16:51
Thanks and no problem. I will check to see whether it's actually an issue or something I'm doing wrong. If it is an issue I'll amend the code I created to show as a reproducible issue. I will leave this ticket open for you to close when you are happy with everything. And once again, a big thank you for such a quick and positive response.

**Comment by codex70** [comment] 2022-12-13 17:56
Actually, running another test, it looks like the profiles are working as expected, I will check again if I'm doing something wrong on my main application.

**Comment by ryanjbaxter** [comment] 2022-12-14 23:51
Agree thanks for helping here!

**Closed** 2022-12-14 23:51 UTC
Labels: waiting-for-triage
