### ISSUE TITLE
`No reload will take place` issue with jasypt-spring-boot-starter-2.0.0

### ISSUE THREAD

**Issue by melonicecream** [spring-cloud/spring-cloud-kubernetes#427] opened 2019-07-19 00:03 UTC
Hello. 
When ConfigMap change detected, logged always `... No reload ...`.
(event, polling both happened)
i think cause i am using the property encryption library, jasypt.
non jasypt used `CompositePropertySource` from `environment.getPropertySources()`, but with jasypt used `EncryptableEnumerablePropertySourceWrapper`.

`EncryptableEnumerablePropertySourceWrapper` is not instance of `CompositePropertySource`(in findPropertySources method). So, always failed checking.

I do not know how can i resolve.
Sorry for bad english.

dependency:
- jasypt-spring-boot-starter-2.0.0
- spring-cloud-kubernetes-config-1.0.2-release

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/d6e4118bf2866054f0e6513c8611669e9689dcf0/spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/reload/ConfigurationChangeDetector.java#L97

**Comment by ryanjbaxter** [comment] 2019-07-19 00:06
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spencergibb** [comment] 2019-07-19 00:08
I'm a bit unsure what you are asking? We don't maintain jasypt. Is there an exception happening?

**Comment by spring-issuemaster** [comment] 2020-04-08 14:55
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-04-15 14:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-04-15 14:55 UTC
Labels: feedback-reminder, waiting for feedback
