### ISSUE TITLE
spring-cloud-starter-kubernetes-fabric8-config breaks unit tests

### ISSUE THREAD

**Issue by adzubla** [spring-cloud/spring-cloud-kubernetes#1204] opened 2023-01-25 15:52 UTC
When I run unit tests and `spring-cloud-starter-kubernetes-fabric8-config` is declared as a dependency, the test breaks with `unresolved namespace`

Look at these logs:
```
2023-01-25 11:07:13.516  WARN 12104 --- [           main] ubernetesProfileEnvironmentPostProcessor : Not running inside kubernetes. Skipping 'kubernetes' profile activation.
2023-01-25 11:07:13.901  WARN 12104 --- [           main] io.fabric8.kubernetes.client.Config      : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2023-01-25 11:07:13.904  WARN 12104 --- [           main] io.fabric8.kubernetes.client.Config      : Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2023-01-25 11:07:14.185 ERROR 12104 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.cloud.kubernetes.commons.config.NamespaceResolutionFailedException: unresolved namespace
	at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigUtils.getApplicationNamespace(Fabric8ConfigUtils.java:107) ~[spring-cloud-kubernetes-fabric8-config-2.1.5.jar:2.1.5]

java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.cloud.kubernetes.commons.config.NamespaceResolutionFailedException: unresolved namespace
```

Although it detects its not inside kubernetes and skips the profile, its still looking for kubernetes configs.

Sample code that demonstrates this issue is available at https://github.com/adzubla/cloud-starter-kubernetes-test (just run mvn test)

**Comment by wind57** [comment] 2023-01-25 16:26
what version are you running? upgrading to the latest `3.x.x` should solve this. Also, if this is just for tests, you could specify some dummy namespace to make your tests happy, for example this env variable: `SPRING_CLOUD_KUBERNETES_CLIENT_NAMESPACE=default`. Look more here : https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1089 

This looks like that duplicate and if such, you can close this one as a duplicate. thank you.

**Comment by wind57** [comment] 2023-01-26 05:45
@ryanjbaxter can be closed as a duplicate of [this](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1089)

**Closed** 2023-01-26 19:19 UTC
Labels: duplicate

**Comment by adzubla** [comment] 2023-01-30 11:34
I can confirm that it works after  upgrading to Spring Boot 3 *and* Spring Cloud 2022.

If you still need to use Spring Boot 2, a workaround is to define this system property when running the tests:
```
mvn test -Dspring.cloud.kubernetes.enabled=false
```

or add this property in the test itself:

```
@TestPropertySource(properties = {"spring.cloud.kubernetes.enabled=false"})
```
