### ISSUE TITLE
Interfering with Spring Cloud Stream, service bus stream binder

### ISSUE THREAD

**Issue by jemag** [spring-cloud/spring-cloud-kubernetes#651] opened 2020-10-01 22:47 UTC
**Currently using:**
- spring cloud Hoxton.SR3
- spring-cloud-azure-servicebus-topic-stream-binder:1.2.7
- spring-cloud-starter-kubernetes-config:1.1.5.RELEASE
- spring-cloud-starter-kubernetes:1.1.5.RELEASE

**Bug**
Messages received using spring cloud stream and servicebus topic stream binder somehow trigger side effects within spring-cloud-kubernetes. For some reason, it seems to be trying to instantiate KubernetesClient from the messages:

> 2020-10-01 13:30:51.752  INFO 1 --- [rvice-handler-0] o.s.i.dispatcher.UnicastingDispatcher    : An exception was thrown by 'ServiceActivator for [org.springframework.integration.handler.MethodInvokingMessageProcessor@28144ea2]' while handling 'GenericMessage [payload=byte[1580], headers={id=99bf73ff-c17f-8ea9-ae03-23e2211cbd6c, raw_id=6f81cfb6-7703-400e-85e1-4e2eed589709, contentType=application/json, timestamp=1601559051751}]': Could not read JSON: Cannot construct instance of `io.fabric8.kubernetes.client.KubernetesClient` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
>  at [Source: (byte[])"{"ipAddress":"XXXXXXX","code":"XXXX"[truncated 1080 bytes]; line: 1, column: 1]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.fabric8.kubernetes.client.KubernetesClient` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information

This will basically keep getting thrown in logs. The method receiving the messages is using a simple Transformer to receive the message, modify it, and send it to another channel:
``` java
  @Transformer(inputChannel = Processor.INPUT, outputChannel = Processor.OUTPUT)

```

**Comment by rattek** [comment] 2020-10-15 20:43
We are experiencing the same problem within my organization.... Any ideas on how to manualy exclude any dependencies related to this error?

**Comment by ryanjbaxter** [comment] 2020-10-19 15:21
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by jemag** [comment] 2020-10-20 14:56
This project replicates the bug for us, when plugged into our service bus: https://github.com/jemag/demo-issue-651/

If you want to run it, just make sure input and output are properly configured for your service bus and that the input is receiving messages while the application is running (exception happens when receiving messages).

**Comment by ryanjbaxter** [comment] 2021-01-20 21:47
Can you please try this again with Hoxton.SR9 and be sure to use the Spring Cloud BOM?

**Comment by spring-cloud-issues** [comment] 2021-01-27 21:52
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-02-03 21:51
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-02-03 21:51 UTC
Labels: feedback-reminder, waiting for feedback
