### ISSUE TITLE
IPv6 support not available in Spring Cloud Kubernetes load balancer

### ISSUE THREAD

**Issue by aakdixit** [spring-cloud/spring-cloud-kubernetes#1078] opened 2022-09-19 12:25 UTC
**Describe the bug**
While using Spring cloud kubernetes loadbalancer in IPv6 setup it is not redirecting the request to IPv6 host and throwing following exception
Error Invalid character ':' for HOST_IPV4 in \"240b:c0e0:202:55a2:b414:2:0:5287\"
The issue is in org.springframework.cloud.kubernetes.commons.discovery.KubernetesServiceInstance class 	
private URI createUri(String scheme, String host, int port) {
		return URI.create(scheme + COLON + DSL + host + COLON + port);
	}
There should be IPv6 check before formulating this URI.

**Sample**

**Comment by aakdixit** [comment] 2022-09-20 16:06
Did you try with configuring kubernetes service with IPv6 endpoint.
Actually the URI created for KubernetesServiceInstance  is http://240b:c0e0:202:55a2:b414:2:0:5287:8000 . Now when we try to send the request to this URI, it is not able to send since IPv6 host address should be covered in square brackets i.e. the UR should be http://[240b:c0e0:202:55a2:b414:2:0:5287]:8000

**Comment by ryanjbaxter** [comment] 2022-09-20 17:33
Could you provide a sample app that demonstrates the problem?

**Comment by spring-cloud-issues** [comment] 2022-09-27 17:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by aakdixit** [comment] 2022-10-02 07:54
Hi Ryan Sorry for late reply. For below mentioned code it throws NumberFormatException because the URI generated by KuberenetesServiceInstance is not taking care of IPv6 and it is not able to get the port 

`KubernetesServiceInstance kubernetesServiceInstance =  new KubernetesServiceInstance("instanceId",  "serviceId",
                "240b:c0e0:202:55a2:b414:2:0:5287", 8000,
                null, false);
        System.out.println("kubernetesServiceInstance.getUri()=="+kubernetesServiceInstance.getUri());
        URI newURI = UriComponentsBuilder.fromHttpUrl(kubernetesServiceInstance.getUri().toString()).query("id={id}")
                .build("123");
        `

**Comment by ryanjbaxter** [comment] 2022-10-04 14:38
I was trying to reproduce this error with a real cluster but I was unable to, so I am looking for how to reproduce the error when running against an actual cluster that is using IPV6

**Comment by spring-cloud-issues** [comment] 2022-10-11 14:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-10-18 14:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-10-18 14:42 UTC
Labels: waiting for feedback, feedback-reminder
