### ISSUE TITLE
I use 1.1.6. Release in spring cloud kubernetes spring.cloud.kubernetes.ribbon.mode=SERVICE , Null pointer exception in getting service list

### ISSUE THREAD

**Issue by GodCaning** [spring-cloud/spring-cloud-kubernetes#641] opened 2020-09-23 03:00 UTC
`java.lang.NullPointerException: null\n\tat org.springframework.cloud.kubernetes.ribbon.KubernetesServicesServerList.getUpdatedListOfServers
(KubernetesServicesServerList.java:80)\n\tat com.netflix.loadbalancer.DynamicServerListLoadBalancer.updateListOfServers(DynamicServerListLoadBalancer.java:240)\n\tat com.netflix.loadbalancer.DynamicServerListLoadBalancer.restOfInit(DynamicServerListLoadBalancer.java:144)\n\tat com.netflix.loadbalancer.DynamicServerListLoadBalancer.<init>(DynamicServerListLoadBalancer.java:95)\n\tat com.netflix.loadbalancer.ZoneAwareLoadBalancer.<init>(ZoneAwareLoadBalancer.java:82)\n\tat org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration.ribbonLoadBalancer(RibbonClientConfiguration.java:155)\n\tat 

`

There is a little problem with the 80 line null logic

`					if (Utils.isNotNullOrEmpty(this.getPortName())
							|| this.getPortName().endsWith(servicePort.getName())) {
						result.add(new Server(concatServiceFQDN(service),
								servicePort.getPort()));
					}`

**Comment by kazakovav** [comment] 2020-10-02 14:44
Hello, I have this problem too.

**Comment by ryanjbaxter** [comment] 2020-10-19 15:32
I'm guess it's `servicePort` that is `null`.  Could you show me the YAML for the service?  Wondering why there is a `null` port.  Even better if you have a sample that reproduces this that would be great.

**Comment by ryanjbaxter** [comment] 2020-11-30 21:49
@GodCaning @kazakovav bump

**Comment by spring-issuemaster** [comment] 2020-12-07 22:09
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-12-14 22:09
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-12-14 22:09 UTC
Labels: bug, feedback-reminder, waiting for feedback
