### ISSUE TITLE
ConfigMap with multiple yaml files and bootstrap.yaml one of them

### ISSUE THREAD

**Issue by bilak** [spring-cloud/spring-cloud-kubernetes#640] opened 2020-09-22 13:40 UTC
**Describe the bug**
Hello,
I'm trying to find out the way how to provide local development and also configure application for kubernetes. 
So for local development we are using something like this structure:
```
application/
├── config/
│   ├── application.yaml
│   ├── bootstrap.yaml
└── src/
    └── main/
        └── resources/ 
            ├── application.yaml
            └── bootstrap.yaml
```

so in `config/` folder we have configuration for our local development
in `resources/` folder we have configuration with defaults which we don't want to override

and in configmap I'd like to use something like this: 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}
data:
  application-kubernetes.yaml: |-
    ...
  bootstrap-kubernetes.yaml: |-
    ...
```
where I'd like to provide only the configs that I want to change for kubernetes.

However it looks like the `bootstrap-kubernetes.yaml` file didn't took effect. 

Is such patter available or what whould be the best option to provide also configuration for `boostrap.yaml`?

**Comment by bilak** [comment] 2020-10-05 14:15
@ryanjbaxter can you plese tell me more to this. So is it possible to have bootstrap loaded from kubernetes or not? Thanks

**Comment by ryanjbaxter** [comment] 2020-10-05 14:52
@bilak could you try keeping the profile configuration in a single bootstrap.yaml file?  for example

```
spring:
.....
---
spring:
  profiles: kubernetes
  cloud:
    kubernetes:
....
```

**Comment by bilak** [comment] 2020-10-05 16:04
@ryanjbaxter that could be an option to use one `bootstrap.yaml|properties`, but is it supported to load bootstrap from kuberntes configmap? I can only see in documentation that it's talking about `application.properties|yaml`. I'm asking because we have functionality that loads config only from `bootstrap.yaml|properties` and I'm wondering whether I can configure that with this library.
Can I somehow raise feature request to support multiple files loaded from configmap (as in my example application + bootstrap yamls)?

**Comment by spencergibb** [comment] 2020-10-05 16:14
Mounted configmaps should work for bootstrap

**Comment by ryanjbaxter** [comment] 2020-10-12 15:24
If I had to guess as to the problem, it would be that the kubernetes profile is not activated in the bootstrap phase, are you just relying on Spring Cloud Kubernetes to add the profile?

have you tried setting the environment variable `SPRING_PROFILES_ACTIVE` or setting the property when the application starts `-Dspring.profiles.active`?

**Comment by bilak** [comment] 2020-10-12 15:35
@ryanjbaxter actually we are setting it to jib so it should be loaded by app

```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>${jib-maven-plugin.version}</version>
    <configuration>
        <to>
            <image>${docker.image.name}:latest</image>
            <tags>
                <tag>${git.commit.id}</tag>
            </tags>
        </to>
        <container>
            <jvmFlags>
                <jvmFlag>-Dspring.profiles.active=kubernetes</jvmFlag>
                <jvmFlag>-Djava.security.egd=file:/dev/./urandom</jvmFlag>
            </jvmFlags>
        </container>
    </configuration>
</plugin>
```

**Comment by ryanjbaxter** [comment] 2020-10-12 15:39
I will need to look into it

**Comment by ryanjbaxter** [comment] 2020-10-16 00:09
This is kind of an interesting problem.  The problem is here 

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-config/src/main/java/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java#L161

When there are multiple files defined in a single configmap they need to be named application.yaml application.yml or application.properties.  Since you have `-kubernetes` appended and you also have `bootstrap-kubernetes` we just make the file name the key and the content the value.

If you hit `/actuator/env` I am sure you will see that in the output.

I dont see a reason why the file name really matters in the case of using the API to read the ConfigMap and we wouldnt head down this path when reading from a path.  I think the fix is really just to check that the file extension in the configmap is either yaml yml or properties.

The interesting problem has to do with profiles....I am not sure how to do that at the moment.  You could have application-dev.yaml and application-production.yaml for example and right now that would all be combined into one property source.

The best workout I can offer at the moment would be to separate the files into different configmaps.

**Comment by hairinwind** [comment] 2021-03-31 21:04
Is there a plan for when it will be fixed?

I think my issue is related to this. If I load multiple application yaml files into configmap, it only picks the application.yaml. I pretty sure my profile is set to dev. But it still picked up the values from application.yml
My configmap is like this. 
```
{
	"application-dev.yml": "config.msg: test message from dev profile...v3...
		welcome.message: welcome from dev profile...v3...
		",
	"application.yml": "config.msg: test message from configmap
		welcome.message: welcome from configmap
		"
}
```

If I put all profiles into one application.yml and load that into configmap. It works properly. I could get the values for dev profile. 
```
{
	"application.yml": "config.msg: test message from configmap...v1...
		welcome.message: welcome from configmap...v2...
		---
		spring:
		  profiles: dev
		config.msg: test message from dev profile...v3...
		welcome.message: welcome from dev profile...v3...
		"
}
```

We have a lot of profiles yaml files under one folder. I don't want to merge them into one. It is easy to load those files into configmap directly. 

Thanks !!!

**Comment by ryanjbaxter** [comment] 2021-03-31 21:19
We can try and get to it, but if anyone is willing to help that would be much appreciated

**Comment by wind57** [comment] 2022-06-13 11:30
I could take a stab at this one, but imo, we need to establish some (documented) rules here.

here is my proposal:

 - if there is a single key in the configmap and it ends in `yaml/yml/properties` - treat it as a "file", we don't care about its name. (this is the current behavior)
 - there are more than one entries in the configmap.  Search for ones that have `<SPRING_APPLICATION_NAME>.yaml/yml/properties` (or `application.yaml/yml/properties` if `SPRING_APPLICATION_NAME` is missing) + all their profile based ones. For example, let's suppose that 

`spring.application.name=my-name` and active profiles = `k8s`; a config like:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-configmap
data:
  my-name.yaml: |-
    ...
  my-name-k8s.yaml: |-
    ..
my-name-dev.yaml: |-
   ..

someProp: someValue
```

This will result in _three_ entries being read:

-  `my-name.yaml` treated as a file
-  `my-name-k8s.yaml` treated as a file
-  `my-name-dev.yaml` _ignored_ since there is no such profile `dev` active
-  `someProp: someValue` plain property

If you agree, or have any other suggestions, do let me know; when I get a green light, I will implement this. 
thank you

**Comment by wind57** [comment] 2022-06-14 06:45
[PR is out for this one, pending review](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1032)

**Closed** 2022-06-16 19:09 UTC
Labels: bug
