### ISSUE TITLE
KubernetesServerList NullPointerException when accessing subset

### ISSUE THREAD

**Issue by alvgarvilla** [spring-cloud/spring-cloud-kubernetes#140] opened 2017-11-16 09:09 UTC
Class org.springframework.cloud.kubernetes.ribbon.KubernetesServerList 

I am getting NullPointerException when trying to access the subsets from the endpoints. Endoints is not null but subsets list is.
```

if (endpoints != null) {

            if (LOG.isDebugEnabled()) {
                LOG.debug("Found [" + endpoints.getSubsets().size() + "] endpoints in namespace [" +
                        namespace + "] for name [" + serviceId + "] and portName [" + portName + "]");
            }
            for (EndpointSubset subset : endpoints.getSubsets()) { <--------

                if (subset.getPorts().size() == 1) {
```

**Comment by IvanAR** [comment] 2018-02-19 14:33
+1 same problem here... @alvgarvilla any workaround?

**Comment by IvanAR** [comment] 2018-02-19 16:34
I got the error, I was setting the wrong label to link Service with the Deployment on Kuberntes, and then no endpoint were been created.  
Check if your service has an endpoint with `kubectl get endpoint`.  
The NullPointer could be changed by some better error message.

**Comment by nieldw** [comment] 2018-04-25 12:59
I experience this if an endpoint goes away after Zuul started.
To reproduce it, start Zuul with at least one pod providing a live endpoint for a particular service. Then bring down that pod. The failure starts as soon as Zuul tries to update it's list of available servers.

**Comment by spencergibb** [comment] 2019-01-29 00:54
Is this still an issue?

**Comment by spring-issuemaster** [comment] 2019-02-05 00:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by alvgarvilla** [comment] 2019-02-06 12:10
As @IvanAR pointed out, I think it is more an issue of which exception is thrown and logged. Having a service without pods attached to it is something that Kuberetes allow so probably an error message informing would be enough. I can make the PR if we agree :)

**Comment by spencergibb** [comment] 2019-02-06 16:22
@alvgarvilla PRs welcome. The code is likely changed. Can you let us know if it is still a problem?

**Comment by spring-issuemaster** [comment] 2019-02-13 16:26
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-20 16:22
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-20 16:22 UTC
Labels: feedback-reminder, waiting for feedback
