### ISSUE TITLE
miss spring-cloud-starter-kubernetes-ribbon:jar:1.1.2.RELEASE

### ISSUE THREAD

**Issue by ToQuery** [spring-cloud/spring-cloud-kubernetes#542] opened 2020-03-31 13:32 UTC
**Describe the bug**
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-starter-kubernetes-ribbon/1.1.2.RELEASE/spring-cloud-starter-kubernetes-ribbon-1.1.2.RELEASE.pom
[WARNING] The POM for org.springframework.cloud:spring-cloud-starter-kubernetes-ribbon:jar:1.1.2.RELEASE is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-starter-kubernetes-ribbon/1.1.2.RELEASE/spring-cloud-starter-kubernetes-ribbon-1.1.2.RELEASE.jar

**Sample**
 <spring-cloud.version>Hoxton.RELEASE</spring-cloud.version>

<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.6.RELEASE</version>
        <relativePath/> 
    </parent>

**Comment by rafaelrenanpacheco** [comment] 2020-03-31 17:21
Duplicate of #530

**Closed** 2020-03-31 17:26 UTC
Labels: waiting-for-triage
