### ISSUE TITLE
kubernetes.secret.source it's not working like configmap configuration

### ISSUE THREAD

**Issue by raphaellins** [spring-cloud/spring-cloud-kubernetes#863] opened 2021-09-05 19:09 UTC
I'm doing some experimentation here with spring-cloud-kubernetes using configmap and secrets

The configuration _spring.cloud.kubernetes.config.sources_ works pretty good, but when i try to use this approach for secrets _spring.cloud.kubernetes.secrets.sources_ it's not working, my secrets only works when i use _spring.cloud.kubernetes.secrets.paths_ with the deployment volumes configured.

I'm trying to use that property wrong? i  can't use just the kubernetes secret name, and i need to mount the volume always?

Thanks, if more info will necessary, i can provide, my example is very simple.

**Comment by wind57** [comment] 2021-09-06 02:38
yes an example would be helpful, like a github repo where we can take a look. anything that is _reproducible_ will do. thank you

**Comment by iiit-rohit** [comment] 2022-08-17 10:37
Is this issue still there ? I am facing some issues while reading secrets using spring.cloud.kubernetes.secrets.sources (list) in bootstrap file. I am only specifying name of the secrets (not path, labels etc) in the bootstrap.yaml file. 

Warning message in the logs :: Can't read secret with name: [XXXX] or labels [{}] in namespace: [default] (cause: null). Ignoring.

**Comment by wind57** [comment] 2022-08-17 10:40
we need a lot more details then just the error message, a _sample_ in github where we can reproduce this is what I have asked before and will ask you also. Is it possible to provide one?

**Comment by iiit-rohit** [comment] 2022-08-18 08:25
Thanks for the quick response. Unfortunately I can not provide you any repo link but I am listing down some details which I have:

**bootstrap.properties**

spring.application.name=demo-service
spring.cloud.kubernetes.secrets.enabled=true
spring.cloud.kubernetes.secrets.sources[0].name=secret-a
spring.cloud.kubernetes.secrets.sources[1].name=secret-x
spring.cloud.kubernetes.secrets.sources[2].name=secret-y
.
.
.


**secret-a**
data:
  dbname: cHJpG1fmk
  password: e29aLZitdfr
kind: Secret
metadata:
  name: secret-a
  namespace: default
  .
  .
  .
type: Opaque

**secret-b**
data:
  dbname: pbS1hZG1
  password: sT3ZaRXZi
kind: Secret
metadata:
  name: secret-b
  namespace: default
  .
  .
  .
type: Opaque

 **Dependency added**

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
</dependency>
Kubernetes Client Dependency
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-client-config</artifactId>
</dependency>

 **Issue observed**

I have enabled fabric8 logs and observed below issues:

1- I can see that all the secrets (preset into the default namespace) are loaded insted of the specified secrest in the bootstrap.properties.

2- In my application i am reading password from secret-a but somehow the value is overriden by password of secrect-b (note that secret-b is not part of bootstrap.properties file).

3- Apart from above, I can also see some warning logs "Can't read secret with name: [secret-a] or labels [{}] in namespace: [default] (cause: null). Ignoring". This messages is coming for all listed secrets in the bootstrap.properties file.

**Comment by iiit-rohit** [comment] 2022-08-25 05:12
@raphaellins Is the above example similar to your example?

**Comment by spring-cloud-issues** [comment] 2023-01-20 21:22
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-01-27 21:22
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-01-27 21:22 UTC
Labels: waiting for feedback, feedback-reminder
