### ISSUE TITLE
Add `spring.cloud.kubernetes.enabled` property 

### ISSUE THREAD

**Issue by akuma8** [spring-cloud/spring-cloud-kubernetes#492] opened 2019-12-01 17:06 UTC
It seems like that property  `spring.cloud.kubernetes.enabled` is not provided. On my dev machine I would like to disable k8s aware but it is not possible. I tried this configuration:
```
spring:
  cloud:
    kubernetes:
      enabled: false # This property does not exist
      secrets:
        enable-api: false
      config:
        enable-api: false
        enabled: false 
```
but when I start my application I have this exception:
```
2019-12-01 | 17:46:49.858 | 24868 |  WARN | [gateway,,,ASUS-ROG] | restartedMain | o.s.c.k.c.ConfigMapPropertySource | Can't read configMap with name: [gateway] in namespace:[dev]. Ignoring.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: [gateway]  in namespace: [dev]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:229)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:162)
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.getData(ConfigMapPropertySource.java:95)
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySource.<init>(ConfigMapPropertySource.java:76)
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:95)
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:78)
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator$$Lambda$395.000000008E0BF780.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.springframework.cloud.kubernetes.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:77)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:98)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at fr.app.GatewayApplication.main(GatewayApplication.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:110)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$$Lambda$234.000000008D0CD880.intercept(Unknown Source)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:404)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:365)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:330)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:311)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:810)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:218)
	... 20 common frames omitted
```
I can use maven profiles to exclude Spring Cloud K8S dependencies but I need them for configuration. 
To confirm the absence of  `spring.cloud.kubernetes.enabled` I also took a look here: https://cloud.spring.io/spring-cloud-static/Hoxton.RELEASE/reference/html/spring-cloud-hoxton-configprops.html and the property is not present.  
Thanks

**Comment by TYsewyn** [comment] 2019-12-10 16:50
Updated documentation with d3700c5 and 98c7eb5. Will verify if it's a bug later tomorrow.

**Comment by TYsewyn** [comment] 2019-12-11 14:57
@akuma8 Can you confirm that this is happening during the bootstrap phase when `spring-cloud-kubernetes-config` is on the classpath?
If this is true, could you check if the stacktrace is gone when you add `spring.cloud.kubernetes.enabled=false` to `bootstrap.properties|yml`?

**Comment by akuma8** [comment] 2019-12-15 10:47
@TYsewyn This is my dependency: 
```
 <spring-cloud.version>Hoxton.RELEASE</spring-cloud.version>

 <dependency>
       <groupId>org.springframework.cloud</groupId>
       <artifactId>spring-cloud-starter-kubernetes-all</artifactId>
          <exclusions>
              <exclusion>
                  <groupId>org.springframework.cloud</groupId>
                  <artifactId>spring-cloud-kubernetes-ribbon</artifactId>
              </exclusion>
          </exclusions>
  </dependency>
```
The property `spring.cloud.kubernetes.enabled`  does not exist actually so I can't set it in `bootstrap.yml`

**Comment by TYsewyn** [comment] 2019-12-15 11:16
What exactly do you mean with “does not exist”?
If you are referring to the code completion and hints within IntelliJ, that will be fixed alongside the documentation in the next release.
That property is used multiple times in the code base, it just wasn’t documented properly.

Have you actually tried setting that property and starting your application?

**Comment by ryanjbaxter** [comment] 2019-12-16 15:23
Going to close this as @TYsewyn should have fixed the documentation as well as the IDE bug with the commits above

**Closed by ryanjbaxter** 2019-12-16 15:23 UTC
Labels: documentation, waiting for feedback

**Comment by akuma8** [comment] 2019-12-19 18:24
> What exactly do you mean with “does not exist”?
> If you are referring to the code completion and hints within IntelliJ, that will be fixed alongside the documentation in the next release.
> That property is used multiple times in the code base, it just wasn’t documented properly.
> 
> Have you actually tried setting that property and starting your application?

Sorry to answer lately, I am a bit busy. 
Yes I did the test. I set the property to `false` and restart my application and still get the exception. Since it's a `WARN` message I ignore it.

**Comment by ryanjbaxter** [comment] 2019-12-19 21:29
Just because IntelliJ does not know about it doesn't mean it doesn't work.  @TYsewyn fixes will make IntelliJ pick them up once we do the next release.

**Comment by akuma8** [comment] 2019-12-20 16:47
@ryanjbaxter I agree with you but I still don't understand why setting that property does not have any effect and I still have the error message during the bootstrap phase.

**Comment by ryanjbaxter** [comment] 2019-12-20 21:05
Can you provide a sample that reproduces the error and problem?

**Comment by akuma8** [comment] 2019-12-28 18:14
@ryanjbaxter See a demo here: https://github.com/akuma8/demo
At the application startup you will see the warning message.

**Comment by TYsewyn** [comment] 2019-12-28 22:58
Like I already said, please add `spring.cloud.kubernetes.enabled: false` to your bootstrap.yml file.

**Comment by akuma8** [comment] 2019-12-30 18:13
Could you set this information in the documenation? I mean setting the property in ` bootstrap.yml` not in `application.yml`

**Comment by TYsewyn** [comment] 2019-12-30 18:46
We would gladly accept any PR for this.
Let me know if you want to take this up! 🙂

**Comment by akuma8** [comment] 2019-12-31 09:28
Yes, for a first contribution, documentation is the right place to start.
Please let me know how to contribute?

**Comment by MrUstiik** [comment] 2021-07-16 10:22
Still does not work.
