### ISSUE TITLE
Missing documentation about configuration properties

### ISSUE THREAD

**Issue by Lacritz** [spring-cloud/spring-cloud-kubernetes#395] opened 2019-05-02 18:55 UTC
Hi Folks,

We added the starter-kubernetes to our dependencies and actually setup it up like mentioned in the configuration.
```
compile group: 'org.springframework.cloud',
            name: 'spring-cloud-starter-kubernetes',
            version: '1.0.1.RELEASE'
```
We have added the the @EnableDiscoveryClient annotation to our application

```
@SpringBootApplication
@ComponentScan(
    includeFilters = @ComponentScan.Filter(InheritedComponent.class)
)
@EnableFeignClients
@EnableDiscoveryClient
public class Service {
  public static void main(String[] args) {
    SpringApplication.run(Service.class);
  }
}
```

But we had still issues. Debugging the application has shown, that only the `CompositeDiscoveryClient` and the `SimpleDiscoveryClient` are being autowired. 

We resolved the issue adding 
```
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
```
to our configuration. But we totally missed any documentation telling us about that fact.
Is there any issue on our side? We assumed that it's enabled by default and not disabled. 

Best
Lacritz

**Comment by geoand** [comment] 2019-05-04 09:00
@ryanjbaxter @spencergibb is this something we should document do you think?

**Comment by ryanjbaxter** [comment] 2019-05-06 14:14
This is the default
```
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
```
So you should not need to set it.  

I noticed you are not using the Spring Cloud BOM.  Can you please try using that?  If you still have issues please provide a sample that reproduce the problem.

**Comment by spring-issuemaster** [comment] 2019-05-13 14:19
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-05-20 14:15
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-05-20 14:15 UTC
Labels: feedback-reminder, waiting for feedback
