### ISSUE TITLE
configMap lists won't work

### ISSUE THREAD

**Issue by davidkarlsen** [spring-cloud/spring-cloud-kubernetes#445] opened 2019-08-01 22:56 UTC
I have `application.yaml` like:
```
spring:
  cloud:
    kubernetes:
      secrets:
        enabled: true
      config:
        sources:
        - name: ibmcloud-cluster-info
          namespace: kube-public
```
but the CM is never attempted loaded.
The serviceaccount has cluster-admin rolebinding.

Using version: 1.0.2.RELEASE

Log:
```
kubectl -n devops logs icp-automator-fsjetty-79df975875-gn5dp |grep PropertySource
web    |    BootstrapConfiguration.KubernetesPropertySourceConfiguration#configMapPropertySourceLocator matched:
web    |    BootstrapConfiguration.KubernetesPropertySourceConfiguration#secretsPropertySourceLocator matched:
web    |       - @ConditionalOnMissingBean (types: org.springframework.context.support.PropertySourcesPlaceholderConfigurer; SearchStrategy: current) did not find any beans (OnBeanCondition)
web    | 2019-08-01 22:52:39.982  INFO 22 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource {name='composite-configmap', propertySources=[ConfigMapPropertySource {name='configmap.application.devops'}]}
web    | 2019-08-01 22:52:40.002  INFO 22 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: SecretsPropertySource {name='secrets.application.devops'}
web    | 2019-08-01 22:52:40.014 DEBUG 22 --- [           main] iginAwareSystemEnvironmentPropertySource : PropertySource 'systemEnvironment' does not contain property 'spring.profiles.include', but found equivalent 'SPRING_PROFILES_INCLUDE'
web    | 2019-08-01 22:52:52.585 DEBUG 22 --- [           main] iginAwareSystemEnvironmentPropertySource : PropertySource 'systemEnvironment' does not contain property 'slack.botName', but found equivalent 'SLACK_BOTNAME'
web    |       - @ConditionalOnMissingBean (types: org.springframework.context.support.PropertySourcesPlaceholderConfigurer; SearchStrategy: current) did not find any beans (OnBeanCondition)
web    |       - @ConditionalOnBean (types: org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration; SearchStrategy: all) found bean 'org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration' (OnBeanCondition)
```

**Comment by davidkarlsen** [comment] 2019-08-01 23:41
I've debugged a bit more, and the `sources` are never get in order to be set values on. Shouldn't this class be `@Configurable` in order for this to work?

**Comment by ryanjbaxter** [comment] 2019-08-05 14:09
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-08-12 14:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-08-19 14:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-08-19 14:12 UTC
Labels: feedback-reminder, waiting for feedback
