### ISSUE TITLE
Kubernetes config starter add Constraint dependency spring-cloud-starter-bootstrap and ruins app with consul-starter

### ISSUE THREAD

**Issue by pshakhov** [spring-cloud/spring-cloud-kubernetes#999] opened 2022-03-25 08:55 UTC
All we need is only reading configmaps, and we try to use the minimal dependency for this purpose.

**Describe the bug**
Using:
`spring-cloud-starter-kubernetes-config` (2.0.0-M6)
`spring-clous-consul-config` (3.1.0)

After startup application fails with:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method configWatch in org.springframework.cloud.consul.config.ConsulConfigAutoConfiguration$ConsulRefreshConfiguration required a single bean, but 2 were found:
	- configDataConsulConfigProperties: a programmatically registered singleton	- consulConfigProperties: defined by method 'consulConfigProperties' in class path resource [org/springframework/cloud/consul/config/ConsulConfigBootstrapConfiguration$ConsulPropertySourceConfiguration.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

Searching of `configDataConsulConfigProperties` in all scope don`t give me a result.

**Sample**
After Gradle build --scan:
![image](https://user-images.githubusercontent.com/32340504/160086881-6718d7b4-f00d-439d-ae9d-70ca4adce804.png)

Can we disable it by `exclude`?

Or should I use `spring-cloud-starter-kubernetes-client-all` instead `starter-config`?

**Comment by ryanjbaxter** [comment] 2022-03-25 10:33
Try using the spring cloud bom rather than managing dependency versions yourself

**Comment by pshakhov** [comment] 2022-03-25 11:20
@ryanjbaxter , thanks. But we already have on classpath `api(platform("org.springframework.cloud:spring-cloud-dependencies:2021.0.1"))`, which goes with our custom dependency-management-bom (on screenshot). Or its not "spring cloud bom"?
Or i must exclude explicit `implementation("org.springframework.cloud:spring-cloud-starter-kubernetes-config:+")`?

**Comment by ryanjbaxter** [comment] 2022-03-25 11:43
It doesn't make sense why you would have milestone builds on the class path then.  Please provide a sample to reproduce the problem

**Comment by pshakhov** [comment] 2022-03-28 10:48
I can`t provide a sample to reproduce right now, cause our apps uses such properties for deploy to k8s (and custom Gradle plugins), and my example can be irrelevant.

Now i tried with `implementation("org.springframework.cloud:spring-cloud-starter-kubernetes-config:1.1.10.RELEASE")`, and build scan havent `bootstrap` constraint deps, but application not going for configmaps when in logs
`The following 2 profiles are active: "kubernetes", "production"`
`SPRING_CLOUD_KUBERNETES_ENABLED: true`

**Comment by ryanjbaxter** [comment] 2022-03-29 13:49
Without a sample its hard to determine what might be wrong.

**Comment by spring-cloud-issues** [comment] 2022-04-05 13:50
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-04-12 13:50
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-04-12 13:50 UTC
Labels: waiting for feedback, feedback-reminder
