### ISSUE TITLE
Spring Boot 3 - cannot load secrets when 'list' role not configured for 'secrets' resource

### ISSUE THREAD

**Issue by cg1410** [spring-cloud/spring-cloud-kubernetes#1380] opened 2023-07-04 08:42 UTC
**Describe the bug**
In the previous versions of that library (2.1.3) we were able to load secrets on kubernetes cluster without 'list' permission given in the role for Service Account.
For example:
bootstrap configuration
```
spring:
  config:
    activate:
      on-profile: kubernetes
  main:
    banner-mode: "off"
  cloud:
    kubernetes:
      config:
        enabled: true
      discovery:
        enabled: true
      reload:
        enabled: true
      secrets:
        enabled: true
        enable-api: true
        sources:
          - name: some-secret-name
```
and Role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
....
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["secrets"]
   ...
    verbs: ["get", "watch"]
```
Then, in the microservice logs there was a warn that application got 403 error when trying to list secrets in the namespace: **"Message: Forbidden! ... doesn't have permission. secrets is forbidden: User "..." cannot list secrets in the namespace "**

But still, library was able to load secrets, and in the logs we could see the information:
`[BootstrapPropertySource {name='bootstrapProperties-secrets.some-secret-name.some-microservice-namespace'},`

After upgrading to Spring Boot 3.0 wiith the spring-cloud-kubernetes in the version 3.0.3
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8-all</artifactId>
    <version>3.0.3</version>
</dependency>
```
that functionality no longer works.
And in the application logs it is clearly visible why:
`[BootstrapPropertySource {name='bootstrapProperties-secrets..some-microservice-namespace'},`

The secret name is missing from located property source.
After debugging I figured out why is that happening.
Here is the code of class `org.springframework.cloud.kubernetes.commons.config.NamedSourceData`

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/4b2e362e810aa23d41164f7acf0a3370475d0b77/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/NamedSourceData.java#L51-L70

in the line **51** `data = dataSupplier(sourceNames)` the Kubernetes Client is throwing an exception and because of that, variable `data` is still empty - so it DOES NOT contain secret names. So then in the last line before `returrn` the variable `names` will be empty. And the result is following:
`[BootstrapPropertySource {name='bootstrapProperties-secrets..some-microservice-namespace'},`

The question is: is there any way to change that behavior? We would like to stick with current Role solution - we don't want to give container a privilege to list all secrets in the namespace.
As i can see it could probably even work if the dataSupplier would not throw an exception - then that if statement from line **53**
could probably make that working.
The other possibility is to call that if statement just before the return statement.

Please let me know If that is intended behavior or maybe it could be fixed.

**Comment by witek1902** [comment] 2023-07-05 08:17
We noticed exactly the same problem. 
IMO, this is a **breaking change** in library that should either be customizable or should not occur.

**Comment by ryanjbaxter** [comment] 2023-07-27 20:25
It couldn’t hurt to add notes to the breaking changes section

**Comment by emlagowski** [comment] 2023-07-31 12:11
Hey, we also noticed a problem caused by this change.

I understand that the change of major version allows you to create a breaking change, but is it a desired change? In the previous version, it was possible to list specific secret names that the application can get. The current approach forces you to allow ServiceAccount to retrieve all the secrets within the namespace, read them and filter them in the application. Why give such permissions to the application?

It was more secure before that change. If two or more applications share one namespace (for whatever reason) it forces us to allow them to read all secerets. 

Also reading all sources at once when there are a lot of sources and some of them could be large seems problematic.

I think we can help with fixing that, but we need to know if it gonna be merged :)

**Closed** 2023-12-14 21:01 UTC
Labels: documentation
