### ISSUE TITLE
Partial service discovery when all-namespaces property is true

### ISSUE THREAD

**Issue by Jimmy-Newtron** [spring-cloud/spring-cloud-kubernetes#824] opened 2021-07-08 09:05 UTC
**Describe the bug**
I have created a simple REST micro-service that lists all discovered cluster services

I used the following dependency (**this is the problem**)

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-client-all</artifactId>
</dependency>
```

and the following property

```yaml
spring:
  cloud:
   kubernetes: 
     discovery: 
       all-namespaces: true
```

**Sample**

ServiceController.java
```java
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.client.ServiceInstance;
import org.springframework.cloud.client.discovery.DiscoveryClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.ResponseBody;

@RestController
public class ServiceController {
  
  @Autowired
  DiscoveryClient discoveryClient;

  @GetMapping("/services")
	public Iterable<String> findAll() {
    return discoveryClient.getServices();
	}

  @GetMapping("/service/{serviceId}")
  @ResponseBody
	public List<ServiceInstance> getService(@PathVariable String serviceId) {
    return discoveryClient.getInstances(serviceId);
	}
}
```
MyApplication.java
```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@SpringBootApplication
@EnableDiscoveryClient
public class MyApplication {

  public static void main(String[] args) {
    SpringApplication.run(MyApplication.class, args);
  }
}
```

**Workaround**

When using the Fabric8 client the problem disappears
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8-all</artifactId>
</dependency>
```

In the [documentation](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#service-account) it is not clear if we need a ClusterRoleBinding or a simple RoleBinding to access all-namespaces

**Comment by wind57** [comment] 2021-07-08 15:00
"the problem disappears", sorry exactly what problem are you talking about?

**Comment by LaSylv** [comment] 2022-05-12 15:51
Having the same issuer

The property `spring.cloud.kubernetes.discovery.all-namespaces: true` works with the fabric8 implementation, but not with the native one

**Comment by vksaamy** [comment] 2022-10-31 10:53
Tested today and still the issue exists with spring-cloud-starter-kubernetes-discoveryclient version 2.1.4

**Comment by ryanjbaxter** [comment] 2022-11-08 01:23
When I run this integration test, modified with 
```
spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
```
I get services from all namespaces.

https://github.com/spring-cloud/spring-cloud-kubernetes/tree/2.1.x/spring-cloud-kubernetes-integration-tests/discovery/kubernetes-client-discovery

**Comment by spring-cloud-issues** [comment] 2022-11-15 01:26
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by vksaamy** [comment] 2022-11-20 22:46
I tried using this dependency

             <dependency>
			  <groupId>org.springframework.cloud</groupId>
			  <artifactId>spring-cloud-starter-kubernetes-discoveryclient</artifactId>
		</dependency>

and tried to list the services across namespaces using
List<String> svclist = discoveryClient.getServices();
This svclist didn't have all the services from all namespaces but only had services from the same namespace where the calling service existed.

When using 

                  <dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-kubernetes-client-all</artifactId>
		</dependency>
   with cluster role to query API server for services, I was able to get all services from all namespaces.

When using 

             <dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-kubernetes-fabric8-all</artifactId>
		</dependency>
also with cluster role to query API server for services, I was able to get all services from all namespaces.

**Comment by ryanjbaxter** [comment] 2022-11-22 01:37
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2022-11-29 01:41
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ryanjbaxter** [comment] 2022-11-30 20:26
The only usage of discovery client i see in this sample is here https://github.com/vksaamy/Petclinc_spring_cloud_discovery_server/blob/a4979ef47d0b8bbffe39eece935550ba11ef5f72/PetClinic01/visits-svc1/src/main/java/org/springframework/samples/petclinic/visits/DiscoveryConfig.java#L37

And there isn't even a service for that.  

Please simply the sample down to the bare minimum necessary to reproduce the problem.

**Comment by vksaamy** [comment] 2022-11-30 23:21
The method that is used is getVet(Integer vetId) method which is trying to list all the services across all namespaces. It lists only two services - Visits and Discovery service. By right, it should display three services - Visits, Discovery ( in petclinic01 namespace) and Vetssvc2 (in petclinic02) namespace. The REST endpoint to invoke is http://<<visit service IP>>:9284/visits/1 . Pls. refer to the attached log captured.
![DiscoverySvc_Namespace](https://user-images.githubusercontent.com/47584524/204928939-29811b49-8c6b-4d1a-b5a5-b0ba902f80e7.png)

**Comment by ryanjbaxter** [comment] 2022-12-01 01:00
so you are using https://hub.docker.com/r/springcloud/spring-cloud-kubernetes-discoveryserver?

How are you configuring and deploying that?

**Comment by vksaamy** [comment] 2022-12-01 01:46
Yes. from the docker image. The discover server is deployed through the yaml - discoveryserver_deployment.yml under petclinic01/K3S folder. The visitsvc bootstrap.yml point to this server through discovery-server-url: http://spring-cloud-kubernetes-discoveryserver.petclinic01.svc.cluster.local URL.

**Comment by ryanjbaxter** [comment] 2022-12-01 14:10
I dont see where you are telling the discovery server to look across all namespaces by setting `all-namespaces` to `true`

**Comment by vksaamy** [comment] 2022-12-01 14:20
This is the bootstrap.yml file of the visitsvc project. It is configured with discovery server URL and all-namespaces to true.
![bootstrap yml](https://user-images.githubusercontent.com/47584524/205076435-93926e3c-3afd-4199-ba8a-5282906179c3.png)

**Comment by vksaamy** [comment] 2022-12-01 14:22
It is configured in bootstrap.yml file of visits svc.
![bootstrap yml](https://user-images.githubusercontent.com/47584524/205076864-ca119be7-af01-4544-90f8-f4cb6b0a59ef.png)

**Comment by ryanjbaxter** [comment] 2022-12-01 15:29
Since the discovery server is supplying the service data you need to set `all-namespaces` to `true` on the discovery server not on the discovery client.  The easiest way would be to set an environment variable in the deployment yaml of the discovery server.

**Comment by vksaamy** [comment] 2022-12-01 22:54
Setting the env value at discovery server is able to fetch services from all namespaces.  Thanks.

**Comment by vksaamy** [comment] 2022-12-01 23:14
Does this need the visitssvc to assign cluesterrole to query API server? There is error on service start up when i removed the cluster role. Now visitssvc is not supposed to use API server to query any service.
![ClusterRole](https://user-images.githubusercontent.com/47584524/205178838-5a69d20d-97da-435f-bce4-46b0230fd180.png)

**Comment by vksaamy** [comment] 2022-12-01 23:17
Now there is error as it can't query API server because i removed clusterrole for the visitssvc. The visitssvc is not supposed to query API server to discover service. It has to use discovery server to query service.
![Uploading ClusterRole.png…]()

**Comment by ryanjbaxter** [comment] 2022-12-02 00:29
You will need to remove this
https://github.com/vksaamy/Petclinc_spring_cloud_discovery_server/blob/main/PetClinic01/visits-svc1/pom.xml#L127-L136

**Comment by vksaamy** [comment] 2022-12-02 00:40
The error still remains though i removed the dependency.

**Comment by vksaamy** [comment] 2022-12-02 00:50
The reason the dependency was added was to load the config map. Pls. refer to the attached error.
![ConfigFailedtoLoad](https://user-images.githubusercontent.com/47584524/205189830-248a50dd-4bef-43c1-983a-93bb525b84cc.png)

**Comment by ryanjbaxter** [comment] 2022-12-02 00:57
It looks like the InformerDiscoveryClient is still on the classpath, some dependency is pulling that in.  Maybe do a maven tree command and look at which spring-cloud-kubernetes dependencies are on the classpath.

**Comment by vksaamy** [comment] 2022-12-02 01:14
Don't see any InformerDiscoveryClient in the class path. Attached is the dependency tree from maven.

[20221202.log](https://github.com/spring-cloud/spring-cloud-kubernetes/files/10137319/20221202.log)

**Comment by ryanjbaxter** [comment] 2022-12-02 01:20
Try setting `kubernetes.informer.enabled=false`

**Comment by vksaamy** [comment] 2022-12-02 02:58
I tried this and still it is throwing the same exception if that dependency is not there.
![Informer](https://user-images.githubusercontent.com/47584524/205205034-9062aa21-2d0b-4bc7-a5af-105cbfb5e86d.png)

**Comment by ryanjbaxter** [comment] 2022-12-02 10:25
What permissions does the app have?  I am not sure why it's happening.  If you can provide a much simpler sample to reproduce I am happy to look at it further.  The one above is much too complex for me to decipher why this is happening

**Comment by vksaamy** [comment] 2022-12-04 14:22
> Setting the env value at discovery server is able to fetch services from all namespaces. Thanks.
Actually the problem is still there. When i updated the image pull policy to Always and when the dependency for discovery client took effect, the discovery of services were from the same namespace.  This is irrespective of the cluster role assignment.

**Comment by ryanjbaxter** [comment] 2022-12-04 19:56
There is not much more I can suggest until I have a simple reproducible sample to work with

**Comment by vksaamy** [comment] 2022-12-04 23:49
I have updated the project removing codes not needed and updated the github project also with the steps to set up project and test the issue. I believe this setup of multiple namespace is needed to identify this issue.

**Comment by ryanjbaxter** [comment] 2022-12-06 16:26
Once again there is no environment variable setting the `all-namespace` property to true in the deployment of the discovery server
       https://github.com/vksaamy/Petclinc_spring_cloud_discovery_server/blob/eed4c58e775dce2f388d311249a80b54e4786c89/PetClinic03/K3S/discoveryserver_deployment.yml#L67-L83

**Comment by vksaamy** [comment] 2022-12-06 22:31
This env variable was already tested and not working. I added again and tested now. Still showing 1 service only. I have updated the changes to Github.
![DiscoverySvc_Namespace_02](https://user-images.githubusercontent.com/47584524/206037858-2235262a-6a6b-4859-a089-3e97a6806a86.png)

**Comment by ryanjbaxter** [comment] 2022-12-07 00:02
This is the property
```
spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
```

When you translate that to an environment variable it would be `SPRING_CLOUD_KUBERNETES_DISCOVERY_ALL_NAMESPACES`

**Comment by vksaamy** [comment] 2022-12-07 00:36
Added the property, deleted the discovery server deployment and recreated. Service discovery still can get one service only.  Updated yaml checked into github.

**Comment by ryanjbaxter** [comment] 2022-12-07 17:25
Try this
```---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: petclinic03
      labels:
        app: spring-cloud-kubernetes-discoveryserver
      name: spring-cloud-kubernetes-discoveryserver
    spec:
      ports:
        - name: http
          port: 80
          targetPort: 8761
      selector:
        app: spring-cloud-kubernetes-discoveryserver
      type: ClusterIP
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: spring-cloud-kubernetes-discoveryserver
      name: spring-cloud-kubernetes-discoveryserver
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      labels:
        app: spring-cloud-kubernetes-discoveryserver
      name: spring-cloud-kubernetes-discoveryserver:view
    roleRef:
      kind: ClusterRole
      apiGroup: rbac.authorization.k8s.io
      name: namespace-reader
    subjects:
      - kind: ServiceAccount
        namespace: petclinic03
        name: spring-cloud-kubernetes-discoveryserver
        apiGroup: ""
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: namespace-reader
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
        verbs: ["get", "list", "watch"]
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      namespace: petclinic03
      name: spring-cloud-kubernetes-discoveryserver-deployment
    spec:
      selector:
        matchLabels:
          app: spring-cloud-kubernetes-discoveryserver
      strategy:
         type: RollingUpdate
      template:
        metadata:
          labels:
            app: spring-cloud-kubernetes-discoveryserver
        spec:
          serviceAccount: spring-cloud-kubernetes-discoveryserver
          containers:
          - name: spring-cloud-kubernetes-discoveryserver
            image: springcloud/spring-cloud-kubernetes-discoveryserver:2.1.5
            imagePullPolicy: Always
            env:
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_ALL_NAMESPACES
              value: "true"
            readinessProbe:
              httpGet:
                port: 8761
                path: /actuator/health/readiness
            livenessProbe:
              httpGet:
                port: 8761
                path: /actuator/health/liveness
            ports:
            - containerPort: 8761
              name: "disc-port"
```

**Comment by vksaamy** [comment] 2022-12-14 11:38
This environment property in discovery server helps to retrieve services from all namespaces.
env:
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_ALL_NAMESPACES
              value: "true"

**Closed** 2022-12-14 13:47 UTC
Labels: feedback-provided
