### ISSUE TITLE
Failure when acquiring leadership for DefaultCandidate

### ISSUE THREAD

**Issue by henrik242** [spring-cloud/spring-cloud-kubernetes#666] opened 2020-10-23 11:32 UTC
We get a fair amount of these in our logs:
```
Failure when acquiring leadership for 'DefaultCandidate{role=foo_api, id=foo-api-755d6bcc97-5gcw5}':
Failure executing: PUT at: https://10.x.y.1/api/v1/namespaces/default/configmaps/leaders. Message: Operation
cannot be fulfilled on configmaps "leaders": the object has been modified; please apply your changes to the
latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[],
group=null, kind=configmaps, name=leaders, retryAfterSeconds=null, uid=null, additionalProperties={}),
kind=Status, message=Operation cannot be fulfilled on configmaps "leaders": the object has been modified;
please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null,
remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict,
status=Failure, additionalProperties={}).
```
(from [org.springframework.cloud.kubernetes.leader.LeadershipController](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/v1.1.6.RELEASE/spring-cloud-kubernetes-leader/src/main/java/org/springframework/cloud/kubernetes/leader/LeadershipController.java))

Is this a bug in `spring-cloud-kubernetes-leader`, or is something on our side causing this?

We're only using a simple `@Component` for this: 
```
@Component
class LeaderElection(private var context: Context? = null) {

    @EventListener
    fun leadershipGranted(event: OnGrantedEvent) {
        log.info("Leadership granted for role ${event.role}")
        context = event.context
    }

    @EventListener
    fun leadershipRevoked(event: OnRevokedEvent) {
        log.info("Leadership revoked for role ${event.role}")
        context = event.context
    }
    fun isLeader() = context?.isLeader ?: false
}
```
Our application.yml is configured with:
```
spring:
  cloud:
    kubernetes:
      leader:
        role: foo_api
        namespace: default
        enabled: true
      client:
        namespace: default
```

**Comment by ryanjbaxter** [comment] 2020-11-30 21:26
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2020-12-07 21:29
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-12-14 21:29
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-12-14 21:29 UTC
Labels: feedback-reminder, waiting for feedback
