### ISSUE TITLE
CPU Spike is observed in the SpringBoot App when a Kubernetes configmap property is changed. The Springboot app is using the  io.fabric8.kubernetes-client for reading the k8s configmap updates. Any help/ suggestions to fix the CPU spike

### ISSUE THREAD

**Issue by dasari-rc** [spring-cloud/spring-cloud-kubernetes#1674] opened 2024-07-12 16:49 UTC
**Describe the bug**
The SpringBoot App deployed as POD in GCP Kubernetes. The Configurations are stored in Configmap & Secrets.
The app is using io.fabric8.kubernetes-client as client to read the changes in Kubernetes Configmap.
We are using @ConfgurationProperties Beans to read the properties from Configmap.
We are seeing a huge spike in configmap when the property in configmap is changed real-time.

**Sample**

My Code snippets below:

We have the SpringBoot app boostrap.properties file as follows:
spring.cloud.kubernetes.config.sources[0].namespace=default
spring.cloud.kubernetes.config.sources[0].name=configmap-name1
spring.cloud.kubernetes.config.sources[1].namespace=default
spring.cloud.kubernetes.config.sources[1].name=configmap-name2
spring.cloud.kubernetes.config.sources[2].namespace=default
spring.cloud.kubernetes.config.sources[2].name=configmap-name3
endpoints.restart.enabled=true
spring.cloud.kubernetes.reload.enabled=true
spring.cloud.kubernetes.reload.strategy=refresh
spring.cloud.kubernetes.reload.mode=event

 <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>5.11.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.yaml</groupId>
                    <artifactId>snakeyaml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.dataformat</groupId>
                    <artifactId>jackson-dataformat-yaml</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

@Data
@Configuration
@ConfigurationProperties
public class K8sConfigmap{
    public String property1;
    public String proerpty2;
  

    @Data
    public static class  Prefix{
        public String subproperty1;
       public String subproperty2;
    }

**Comment by ryanjbaxter** [comment] 2024-07-12 17:22
What version of Spring Cloud?  

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by dasari-rc** [comment] 2024-07-15 14:34
> What version of Spring Cloud?
> 
> Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

We are using SpringBoot 2.7.1 and Spring Cloud Version 2021.0.3.
We are using the following dependencies for Kubernetes Client:

<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
		<exclusions>
            <exclusion>
                <groupId>io.fabric8</groupId>
                <artifactId>kubernetes-client</artifactId>
            </exclusion>
        </exclusions>
        </dependency>
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>5.11.2</version>
        </dependency>

**We are using following bootstrap.properties:**
spring.cloud.kubernetes.reload.enabled=true
spring.cloud.kubernetes.reload.strategy=refresh
spring.cloud.kubernetes.enabled=true
spring.cloud.kubernetes.reload.mode=event

**Comment by dasari-rc** [comment] 2024-07-19 17:50
Also @ryanjbaxter  i was observing one issue not sure if i can attribute it towards the CPU spike.

We have SpringBoot Microservices PODs running in GKE cluster for different domains.
We have created 2 to 3 Configmap for each Microservice for externalizing the configurations. We have configured each Microservice to access these 2 to 3 dedicated Configmaps in the bootstrap.properties file using the following properties -

- spring.application.name=microservice1
- spring.cloud.kubernetes.enabled=true
- spring.cloud.kubernetes.reload.enabled=true
- spring.cloud.kubernetes.reload.mode=event
- spring.cloud.kubernetes.reload.strategy=refresh
- spring.cloud.kubernetes.config.sources[0].namespace=dev
- spring.cloud.kubernetes.config.sources[0].name=configmap-application-common
- spring.cloud.kubernetes.config.sources[1].namespace=dev
- spring.cloud.kubernetes.config.sources[1].name=configmap-address-validation-dev
- spring.cloud.kubernetes.config.sources[2].namespace=dev
- spring.cloud.kubernetes.config.sources[2].name=configmap-application-dev

We have created a service account which can have access ( get, list watch) to all the configmaps.
For each Microservice we have assigned the service account created in the above step. 

We are observing whenever a Realtime update is made to a configmap which is not part of the Microservice bootstrap.properties, still   the class **EventBasedConfigMapChangeDetector** from _org.springframework.cloud.kubernetes.fabric8.config.reload_ package is getting an event in the Microservice and is watching for the event and trying check for any property change which shouldnt have happened.
As we have many PODs spinned up in PROD we are aseeing the CPU usage is crossing Limits and getting restarted.

Can you please help us here.

**Comment by ryanjbaxter** [comment] 2024-07-22 20:02
As @wind57 said 2021.0.x is no longer supported please update to 2023.0.x and see if it make a difference

**Comment by spring-cloud-issues** [comment] 2024-07-31 09:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-08-07 09:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-08-07 09:20 UTC
Labels: waiting for feedback, feedback-reminder
