### ISSUE TITLE
spring boot 2.0 support

### ISSUE THREAD

**Issue by RolandOtta** [spring-cloud/spring-cloud-kubernetes#220] opened 2018-07-26 09:58 UTC
Hello,

as far as i understand, there is still no support for spring boot 2.0. is that right?

any plans when spring boot 2.0 will be supported?

thanks & regards,
roland

**Comment by psoares** [comment] 2018-07-26 13:09
Try version 0.3.0.RC1.

**Comment by RolandOtta** [comment] 2018-07-26 14:59
hi!

thank you ... the sba starts up with that version.

but no pods are discovered .... no suspicios errors in the logs so far.
any advice how i could debug that?

**Comment by prafsoni** [comment] 2018-07-26 20:57
I believe you are trying to discover other services. if that's what you are trying use `spring-cloud-starter-kubernetes-ribbon` and if you want to load config maps too use `spring-cloud-starter-kubernetes-all`

**Comment by RolandOtta** [comment] 2018-07-27 06:31
what i am trying to achieve is to automatically discover applications by springboot admin (without using spring boot admin client in the applications).

so i added spring-cloud-starter-kubernetes in my dependencies of my springboot admin server and enabled discovery by adding @EnableDiscoveryClient

but after starting the springboot admin with that setup no containers are discovered by springboot adnub

**Comment by prafsoni** [comment] 2018-07-30 15:12
Not sure if SBA supports k8s discovery.

**Comment by RolandOtta** [comment] 2018-07-31 11:42
they just say "Spring Boot Admin supports all other implementations of Spring Cloud’s DiscoveryClient" in the docs ... so i thought it should work

**Comment by steven-sheehy** [comment] 2018-08-02 21:51
I don't think spring-cloud-kubernetes implements DiscoveryClient because discovery is automatic in Kubernetes via environment variables or via DNS.

**Comment by spencergibb** [comment] 2018-08-02 21:53
It certainly does implement DiscoveryClient https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java

**Comment by Alos** [comment] 2018-08-15 19:27
I just tried my self. I added:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes</artifactId>
    <version>0.3.0.RELEASE</version>
</dependency>
```
to a Spring Boot Admin instance I got a bunch of errors upon startup:

> Couldn't register instance for service org.springframework.cloud.kubernetes.discovery.KubernetesServiceInstance@793138bd

and 

> "java.lang.NullPointerException: null
> 	at de.codecentric.boot.admin.server.cloud.discovery.DefaultServiceInstanceConverter.getHealthUrl(DefaultServiceInstanceConverter.java:82) ~[spring-boot-admin-server-cloud-2.0.2.jar!/:2.0.2]
> 	at de.codecentric.boot.admin.server.cloud.discovery.DefaultServiceInstanceConverter.convert(DefaultServiceInstanceConverter.java:61) ~[spring-boot-admin-server-cloud-2.0.2.jar!/:2.0.2]
> 	at de.codecentric.boot.admin.server.cloud.discovery.InstanceDiscoveryListener.registerInstance(InstanceDiscoveryListener.java:137) ~[spring-boot-admin-server-cloud-2.0.2.jar!/:2.0.2]
> ..."

**Comment by spencergibb** [comment] 2018-08-15 19:29
We don't support spring boot admin, you'll have to bring it up with them.

**Comment by smartwjw** [comment] 2018-08-22 08:03
I test from springboot 2.2 ~ 2.4, it fails at all tested version.


> 
[2018-08-22 15:56:31,051] [ERROR] [main] org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.duoshengbu.account.Main.main(Main.java:70)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.springframework.core.annotation.AnnotatedElementUtils.hasAnnotation(AnnotatedElementUtils.java:573)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.isHandler(RequestMappingHandlerMapping.java:177)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:217)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:129)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1765)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
	... 16 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:62073', transport: 'socket'

**Comment by Salaboy** [comment] 2018-09-15 08:05
@Alos @smartwjw I got it working, and I will be showing that as S1P in a week time. I am preparing the PRs for their repositories, you can check some draft code here: https://github.com/Salaboy/showcase-admin-tool/

**Comment by Salaboy** [comment] 2018-09-15 08:05
I think that we can close this issue, because spring boot 2 is supported.

**Closed** 2018-10-30 16:43 UTC
Labels: waiting-for-triage
